// Generated by Qleany v1.7.3 from frontend_event_hub_client.tera
//
// Hand-patched: the pump calls each callback with the subscriber map unlocked,
// and a token drops what it removed only after unlocking (see `start` and
// `SubscriptionToken::drop`). The template still generates the locked form, so
// regenerating this file brings the deadlock back until the template is fixed.
use common::event::{Event, EventHub, Origin};
use flume::{Receiver, Selector};
use parking_lot::Mutex;
use std::collections::HashMap;
use std::sync::Arc;
use std::sync::atomic::{AtomicBool, AtomicU64, Ordering};
use std::thread;

/// Event callback type
pub type EventCallback = Box<dyn Fn(Event) + Send>;

/// One subscription as the pump sees it.
///
/// Shared, so the pump can copy the callbacks for an event out of the map and
/// call them with the map unlocked. The mutex is what lets a closure that is only
/// `Send` be shared between threads without asking every subscriber for a `Sync`
/// one; only the pump calls it, so it is never contended.
struct Subscriber {
    callback: Mutex<EventCallback>,
    /// Cleared when the token drops, so a callback removed while an event is being
    /// delivered is skipped if the pump has not reached it yet.
    active: AtomicBool,
}

/// Internal storage: each subscriber entry pairs its id (for O(n) removal on
/// token drop) with its callback. Vec preserves registration order so
/// subscribers fire deterministically.
type SubscriberList = Vec<(u64, Arc<Subscriber>)>;

/// EventHubClient - handles event passing from backend to UI
/// Subscribe callbacks to specific event origins and start the event loop.
#[derive(Clone)]
pub struct EventHubClient {
    subscribers: Arc<Mutex<HashMap<Origin, SubscriberList>>>,
    receiver: Receiver<Event>,
    next_subscriber_id: Arc<AtomicU64>,
}

impl EventHubClient {
    /// Create a new event hub client
    pub fn new(event_hub: &EventHub) -> Self {
        EventHubClient {
            subscribers: Arc::new(Mutex::new(HashMap::new())),
            receiver: event_hub.subscribe_receiver(),
            next_subscriber_id: Arc::new(AtomicU64::new(0)),
        }
    }

    /// Subscribe a callback to an origin. The returned `SubscriptionToken`
    /// removes the callback from the subscribers map when dropped — hold it
    /// for as long as you want the callback to fire, then drop it to
    /// unsubscribe.
    pub fn subscribe<F>(&self, origin: Origin, callback: F) -> SubscriptionToken
    where
        F: Fn(Event) + Send + 'static,
    {
        let id = self.next_subscriber_id.fetch_add(1, Ordering::Relaxed);
        let subscriber = Arc::new(Subscriber {
            callback: Mutex::new(Box::new(callback)),
            active: AtomicBool::new(true),
        });
        {
            let mut subs = self.subscribers.lock();
            subs.entry(origin.clone())
                .or_default()
                .push((id, subscriber));
        }
        SubscriptionToken {
            subscribers: Arc::clone(&self.subscribers),
            origin,
            id,
        }
    }

    /// Start the event loop in a background thread.
    ///
    /// The thread blocks on a `flume::Selector` that waits on either an
    /// incoming event or the shutdown receiver. Zero CPU while idle —
    /// no polling, no timeout. The thread exits when the matching
    /// shutdown `Sender` is dropped (which makes `shutdown_rx`
    /// `Disconnected`) or when the event hub's sender drops.
    pub fn start(&self, shutdown_rx: Receiver<()>) {
        let receiver = self.receiver.clone();
        let subscribers = Arc::clone(&self.subscribers);

        log::info!("EventHubClient starting event loop");

        thread::spawn(move || {
            log::info!("EventHubClient event loop started");
            loop {
                // True blocking wait. Both branches reduce to
                // `Result<Option<Event>, ()>`: `Ok(Some(event))` for a
                // real delivery, `Ok(None)` for shutdown (either the
                // shutdown sender was dropped or a `()` was actually
                // sent), `Err(())` for event-channel disconnect.
                let outcome: Result<Option<Event>, ()> = Selector::new()
                    .recv(&receiver, |r| r.map(Some).map_err(|_| ()))
                    .recv(&shutdown_rx, |_| Ok(None))
                    .wait();
                match outcome {
                    Ok(Some(event)) => {
                        log::debug!("EventHubClient received event: {:?}", event);
                        // Copied out, then called with the map unlocked. A
                        // callback can do anything a subscriber can: drop the last
                        // handle to a document, whose tokens then lock this map to
                        // remove themselves, or wait on a lock held by a thread
                        // that is subscribing at that moment. With the map held
                        // across the call, the first was this thread waiting on
                        // itself and the second a lock-order deadlock with that
                        // thread, and either way every later subscribe and
                        // unsubscribe on this client waited forever.
                        let callbacks: Vec<Arc<Subscriber>> = {
                            let subs = subscribers.lock();
                            subs.get(&event.origin)
                                .map(|list| list.iter().map(|(_, s)| Arc::clone(s)).collect())
                                .unwrap_or_default()
                        };
                        for subscriber in callbacks {
                            if subscriber.active.load(Ordering::Acquire) {
                                (subscriber.callback.lock())(event.clone());
                            }
                        }
                    }
                    Ok(None) => {
                        log::info!("EventHubClient quitting event loop");
                        break;
                    }
                    Err(()) => {
                        log::info!("EventHubClient channel disconnected");
                        break;
                    }
                }
            }
        });
    }
}

/// Opaque handle returned by `EventHubClient::subscribe`. Dropping it removes
/// the associated callback from the subscribers map; the origin's entry is
/// removed entirely when its last subscriber goes away.
///
/// The pump calls callbacks without holding the map, so a drop no longer waits
/// for a delivery in progress: a callback the pump had already started can run
/// to its end after its token dropped, and one it had not reached yet is
/// skipped. A callback therefore has to tolerate running once while its
/// subscriber is going away, as one holding a weak reference does.
pub struct SubscriptionToken {
    subscribers: Arc<Mutex<HashMap<Origin, SubscriberList>>>,
    origin: Origin,
    id: u64,
}

impl Drop for SubscriptionToken {
    fn drop(&mut self) {
        // Best-effort removal. parking_lot mutexes don't poison, so the
        // lock always succeeds (no double-panic risk during unwind).
        let removed = {
            let mut subs = self.subscribers.lock();
            let mut removed = None;
            if let Some(list) = subs.get_mut(&self.origin) {
                if let Some(at) = list.iter().position(|(id, _)| *id == self.id) {
                    removed = Some(list.remove(at).1);
                }
                if list.is_empty() {
                    subs.remove(&self.origin);
                }
            }
            removed
        };
        if let Some(subscriber) = removed {
            subscriber.active.store(false, Ordering::Release);
            // Released only now that the map is unlocked: the callback's
            // captures can own anything, a document whose own tokens lock the
            // map included.
            drop(subscriber);
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use common::event::LongOperationEvent;
    use std::time::Duration;

    /// How long a callback that should run in microseconds is given before the
    /// test calls the pump stuck. Generous, so a loaded CI runner cannot fail it
    /// by being slow; a deadlock fails it the same way however long it is.
    const LIMIT: Duration = Duration::from_secs(10);

    fn progress() -> Origin {
        Origin::LongOperation(LongOperationEvent::Progress)
    }

    fn event(origin: Origin) -> Event {
        Event {
            origin,
            ids: vec![],
            data: None,
        }
    }

    /// A started client, and the sender whose drop stops its pump.
    fn pumped(hub: &EventHub) -> (EventHubClient, flume::Sender<()>) {
        let client = EventHubClient::new(hub);
        let (shutdown_tx, shutdown_rx) = flume::bounded(1);
        client.start(shutdown_rx);
        (client, shutdown_tx)
    }

    /// Subscribes from a thread of its own and reports whether that returned in
    /// time. The subscription is made on another thread so that a client whose
    /// map is held forever fails this test instead of hanging the test binary.
    fn subscribes_in_time(client: &EventHubClient) -> bool {
        let client = client.clone();
        let (done_tx, done_rx) = flume::bounded(1);
        thread::spawn(move || {
            let token = client.subscribe(progress(), |_| {});
            drop(token);
            let _ = done_tx.send(());
        });
        done_rx.recv_timeout(LIMIT).is_ok()
    }

    /// A callback may drop a subscription on the client that is calling it.
    ///
    /// This is what a document does when the pump holds the last handle to it: a
    /// long-operation callback upgrades its weak reference, the host drops every
    /// handle of its own meanwhile, and the document is destroyed on the pump
    /// thread at the end of the callback, taking its subscription tokens with it.
    /// The pump used to call every callback with the subscriber map locked, and a
    /// token removes itself by locking that same map, so the pump waited on itself
    /// forever. Every later subscribe or unsubscribe on the client then waited on
    /// the pump: a host building or dropping any other document in the backend
    /// hung with it.
    #[test]
    fn a_callback_may_drop_a_subscription_without_stopping_the_pump() {
        let hub = EventHub::new();
        let (client, _shutdown) = pumped(&hub);

        let parked: Arc<Mutex<Option<SubscriptionToken>>> = Arc::new(Mutex::new(None));
        let (fired_tx, fired_rx) = flume::unbounded();
        let slot = Arc::clone(&parked);
        let token = client.subscribe(progress(), move |_| {
            // The callback's own token: the case above, where the document being
            // destroyed is the one whose callback is running.
            drop(slot.lock().take());
            let _ = fired_tx.send(());
        });
        *parked.lock() = Some(token);

        hub.send_event(event(progress()));

        assert!(
            fired_rx.recv_timeout(LIMIT).is_ok(),
            "the pump did not come back from a callback that dropped a subscription \
             within {LIMIT:?}: it is waiting on the subscriber map it holds itself"
        );
        assert!(
            subscribes_in_time(&client),
            "the client took no new subscription within {LIMIT:?} after a callback \
             dropped one: the pump never released the subscriber map"
        );
        assert!(
            parked.lock().is_none(),
            "the callback ran, so it must have dropped the token it was handed"
        );
    }

    /// A thread may subscribe while holding a lock that a running callback is
    /// waiting on.
    ///
    /// `TextDocument` subscribes its long-operation callbacks while holding its
    /// own lock, and each of those callbacks takes that lock. In a shared backend
    /// the pump calls a new document's first callback for an operation of any
    /// sibling as soon as it is registered, so the pump can be waiting on the
    /// document lock while the building thread, holding it, subscribes the next
    /// callback. With the map locked across every call that was a lock-order
    /// deadlock between the pump and the host.
    #[test]
    fn subscribing_while_a_callback_waits_on_the_subscriber_does_not_deadlock() {
        let hub = Arc::new(EventHub::new());
        let (client, _shutdown) = pumped(&hub);

        let document_lock = Arc::new(Mutex::new(()));
        let (entered_tx, entered_rx) = flume::unbounded();
        let lock_in_callback = Arc::clone(&document_lock);
        let waiting = client.subscribe(progress(), move |_| {
            let _ = entered_tx.send(());
            drop(lock_in_callback.lock());
        });

        let (done_tx, done_rx) = flume::bounded(1);
        let builder_client = client.clone();
        let builder_hub = Arc::clone(&hub);
        thread::spawn(move || {
            let _held = document_lock.lock();
            builder_hub.send_event(event(progress()));
            // The pump is now inside the callback, about to wait on `_held`.
            if entered_rx.recv_timeout(LIMIT).is_err() {
                return;
            }
            let token = builder_client.subscribe(progress(), |_| {});
            drop(token);
            let _ = done_tx.send(());
        });

        let returned = done_rx.recv_timeout(LIMIT).is_ok();
        if !returned {
            // Dropping the token would lock the map the stuck pump holds, and the
            // test would hang in its own unwinding instead of failing.
            std::mem::forget(waiting);
        }
        assert!(
            returned,
            "subscribing while holding a lock a running callback waits on did not \
             return within {LIMIT:?}: the pump holds the subscriber map across the call"
        );
    }
}
