// Generated by Qleany v1.5.1 from feature_dtos.tera

use common::format_runs::ReplaceFormatPolicy;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct FindTextDto {
    pub query: String,
    pub case_sensitive: bool,
    pub whole_word: bool,
    pub use_regex: bool,
    pub search_backward: bool,
    pub start_position: i64,
}
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct FindResultDto {
    pub found: bool,
    pub position: i64,
    pub length: i64,
}
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct FindAllDto {
    pub query: String,
    pub case_sensitive: bool,
    pub whole_word: bool,
    pub use_regex: bool,
}
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct FindAllResultDto {
    pub positions: Vec<i64>,
    pub lengths: Vec<i64>,
    pub count: i64,
}
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct ReplaceTextDto {
    pub query: String,
    pub replacement: String,
    pub case_sensitive: bool,
    pub whole_word: bool,
    pub use_regex: bool,
    pub replace_all: bool,
    /// What the replacement text wears where it overwrites formatted prose.
    ///
    /// Defaults to the historical behaviour (`InheritPreceding`), which drops the
    /// formatting under the range — fine for plain text, destructive for a rename that
    /// lands on a partly-bold name. See [`ReplaceFormatPolicy`].
    pub format_policy: ReplaceFormatPolicy,
}
#[derive(Debug, Clone, PartialEq, Default, Serialize, Deserialize)]
pub struct ReplaceResultDto {
    pub replacements_count: i64,
    pub skipped_cross_block: i64,
}
