// Generated by Qleany v1.4.8 from feature_lib.tera
pub mod document_search_controller;
pub mod dtos;
// Hand-added (NOT generated by Qleany): the shared matcher. Everything that asks "does
// this text contain that query" goes through it — the in-document find, find-and-replace,
// and, via the public API, a host app's project-wide search. Two matchers would drift.
pub mod folding;
pub mod matching;
mod units_of_work;
pub(crate) mod use_cases;

pub use dtos::*;
