// Generated by Qleany v1.4.8 from feature_use_case.tera
use crate::ExportDjotDto;
use anyhow::{Result, anyhow};
use common::database::QueryUnitOfWork;
use common::database::rope_helpers::block_content_via_store;
use common::entities::{
    Alignment, Block, CharVerticalAlignment, Document, Frame, List, ListStyle, MarkerType, Root,
    SemanticRole, Table, TableCell, TextDirection,
};
use common::format_runs::{InlineContent, InlineSegment};
use common::parser_tools::DjotExportOptions;
// The single definition of both, shared with anything else converting plain text to Djot
// (a host app promoting a stored plain-text field, for one). Kept as aliases so this
// exporter's call sites read as they always did, while there is only one escaper to be
// wrong about the awkward strings.
use common::parser_tools::djot_escape::{
    escape_djot_inline_in_context, guard_djot_attribute_continuation, keep_djot_edge_whitespace,
    reads_as_image_source_escape,
};
use common::parser_tools::escape_djot_inline as escape_djot;
use common::parser_tools::guard_djot_block_start as guard_block_start;
use common::types::{EntityId, ROOT_ENTITY_ID};
use std::borrow::Cow;
use std::collections::HashSet;

pub trait ExportDjotUnitOfWorkFactoryTrait: Send + Sync {
    fn create(&self) -> Box<dyn ExportDjotUnitOfWorkTrait>;
}

#[macros::uow_action(entity = "Root", action = "GetRO")]
#[macros::uow_action(entity = "Root", action = "GetRelationshipRO")]
#[macros::uow_action(entity = "Document", action = "GetRO")]
#[macros::uow_action(entity = "Document", action = "GetRelationshipRO")]
#[macros::uow_action(entity = "Frame", action = "GetRO")]
#[macros::uow_action(entity = "Frame", action = "GetMultiRO")]
#[macros::uow_action(entity = "Frame", action = "GetRelationshipRO")]
#[macros::uow_action(entity = "Block", action = "GetRO")]
#[macros::uow_action(entity = "Block", action = "GetMultiRO")]
#[macros::uow_action(entity = "Block", action = "GetRelationshipRO")]
#[macros::uow_action(entity = "List", action = "GetRO")]
#[macros::uow_action(entity = "Table", action = "GetRO")]
#[macros::uow_action(entity = "Table", action = "GetRelationshipRO")]
#[macros::uow_action(entity = "TableCell", action = "GetMultiRO")]
pub trait ExportDjotUnitOfWorkTrait: QueryUnitOfWork {}

pub struct ExportDjotUseCase {
    uow_factory: Box<dyn ExportDjotUnitOfWorkFactoryTrait>,
    /// Copied off `options` at the top of `execute`. The inline renderer that
    /// needs it is reached both from `render_block_line` (which carries
    /// `options`) and from `render_inline_djot` (which does not), so a
    /// parameter would have to be threaded through a walk that otherwise has no
    /// interest in export settings. Mirrors `ExportMarkdownUseCase::options`.
    omit_images: bool,
}

impl ExportDjotUseCase {
    pub fn new(uow_factory: Box<dyn ExportDjotUnitOfWorkFactoryTrait>) -> Self {
        ExportDjotUseCase {
            uow_factory,
            omit_images: false,
        }
    }

    pub fn execute(&mut self, options: &DjotExportOptions) -> Result<ExportDjotDto> {
        self.omit_images = options.omit_images;
        let uow = self.uow_factory.create();
        uow.begin_transaction()?;

        // Step 1: Get Root and Document
        let root = uow
            .get_root(&ROOT_ENTITY_ID)?
            .ok_or_else(|| anyhow!("Root entity not found"))?;

        let doc_ids = uow.get_root_relationship(
            &root.id,
            &common::direct_access::root::RootRelationshipField::Document,
        )?;
        let doc_id = *doc_ids
            .first()
            .ok_or_else(|| anyhow!("Root has no associated Document"))?;

        let frame_ids = uow.get_document_relationship(
            &doc_id,
            &common::direct_access::document::DocumentRelationshipField::Frames,
        )?;

        // Collect all cell frame IDs so we can skip them in the main loop
        let table_ids = uow.get_document_relationship(
            &doc_id,
            &common::direct_access::document::DocumentRelationshipField::Tables,
        )?;
        let mut cell_frame_ids: HashSet<EntityId> = HashSet::new();
        for tid in &table_ids {
            let cell_ids = uow.get_table_relationship(
                tid,
                &common::direct_access::table::TableRelationshipField::Cells,
            )?;
            let cells_opt = uow.get_table_cell_multi(&cell_ids)?;
            for cell in cells_opt.into_iter().flatten() {
                if let Some(cf_id) = cell.cell_frame {
                    cell_frame_ids.insert(cf_id);
                }
            }
        }

        let mut output_parts: Vec<String> = Vec::new();

        for frame_id in &frame_ids {
            // Skip cell frames — they're rendered as part of their table
            if cell_frame_ids.contains(frame_id) {
                continue;
            }

            // Check if this is a table anchor frame
            let frame = uow.get_frame(frame_id)?;
            // Only render top-level frames (parent_frame == None). Sub-frames
            // (e.g. blockquotes) are recursively rendered from their parent's
            // `render_frame_content` walk; rendering them at the top level
            // again would duplicate their content.
            if let Some(ref f) = frame
                && f.parent_frame.is_some()
            {
                continue;
            }
            if let Some(ref f) = frame
                && let Some(table_id) = f.table
            {
                let table_md = self.render_table_djot(&*uow, &table_id)?;
                if !output_parts.is_empty() {
                    output_parts.push("\n\n".to_string());
                }
                output_parts.push(table_md);
                continue;
            }

            if let Some(ref f) = frame {
                let frame_text =
                    self.render_frame_content(&*uow, f, &cell_frame_ids, "", options)?;
                if !frame_text.is_empty() {
                    if !output_parts.is_empty() {
                        output_parts.push("\n\n".to_string());
                    }
                    // A footnote definition frame is body content that has to
                    // announce whose body it is. Without the `[^label]:` prefix
                    // the note re-parses as an ordinary paragraph sitting where
                    // the definition was typed — the body survives, the fact
                    // that it *is* a note does not.
                    //
                    // Continuation lines are indented, which is how djot marks a
                    // multi-block note body as belonging to the definition
                    // rather than ending it.
                    //
                    // Every one is indented as far as the first line's text
                    // starts, past `[^label]: `, before its own indentation. The
                    // parser takes up to the width of `[^label]:` off each, which
                    // leaves every line of the body one column in, the first
                    // included, and the body's own indentation intact under it.
                    // Lines indented less lost some of their own: with four
                    // spaces, a list nested in a note was read back one level up,
                    // and a code block's indented lines lost a column at every
                    // save, or, indented further than its fence, gained one.
                    if let Some(ref label) = f.footnote_label {
                        let marker = format!("[^{label}]: ");
                        let past_marker = " ".repeat(marker.len());
                        let mut lines = frame_text.lines();
                        let mut out = String::new();
                        if let Some(first) = lines.next() {
                            out.push_str(&marker);
                            out.push_str(first);
                        }
                        for line in lines {
                            out.push('\n');
                            if line.is_empty() {
                                continue;
                            }
                            // A line of whitespace alone (a code block's) is one the
                            // parser takes nothing off, the one column in aside, which
                            // the block's fence stands in and so takes off its lines.
                            if line.chars().all(|c| c.is_ascii_whitespace()) {
                                out.push(' ');
                            } else {
                                out.push_str(&past_marker);
                            }
                            out.push_str(line);
                        }
                        output_parts.push(out);
                    } else {
                        output_parts.push(frame_text);
                    }
                }
            }
        }

        uow.end_transaction()?;

        let djot_text = output_parts.concat();

        Ok(ExportDjotDto { djot_text })
    }

    /// Render the content of a frame by walking its `child_order`.
    /// Positive entries are block IDs, negative entries are negated
    /// sub-frame IDs. `quote_prefix` is prepended to every output line
    /// (e.g. "> " for blockquotes). Returns a single fully-joined
    /// String — inter-block / inter-frame separators are already baked
    /// in. Callers (both `execute` and this function's own recursion
    /// into sub-frames) must NOT add further "\n\n" around the result;
    /// doing so previously produced exponentially many extra blank
    /// lines for nested frames.
    fn render_frame_content(
        &self,
        uow: &dyn ExportDjotUnitOfWorkTrait,
        frame: &Frame,
        cell_frame_ids: &HashSet<EntityId>,
        quote_prefix: &str,
        options: &DjotExportOptions,
    ) -> Result<String> {
        let mut result = String::new();
        // The list levels the parser will have open after the block just written, one per
        // nesting level: they decide how deep the next item may nest and whether it
        // continues a list's numbering. See `render_block_line`.
        let mut open_levels: Vec<OpenLevel> = Vec::new();
        // The frame's semantic role rides its first block and is then spent — a second
        // `{semantic_role=…}` further down would re-open the same claim on a paragraph
        // that is only a continuation of the quote.
        let mut first_block_role = frame.fmt_semantic_role.as_ref();

        // Every block/sub-frame is separated by a blank line. Djot renders the
        // resulting lists "loose", but the model does not distinguish
        // tight/loose, and the blank line is exactly what lets an indented
        // sub-list nest rather than fold into the parent item's paragraph.
        // Inside a quotation the blank line carries the quotation's markers
        // (see `block_separator`).
        let separator = block_separator(quote_prefix);

        // If child_order is empty, fall back to iterating blocks directly
        let use_child_order = !frame.child_order.is_empty();

        if use_child_order {
            for &entry in &frame.child_order {
                if entry > 0 {
                    // Positive: block ID
                    let block_id = entry as EntityId;
                    let block = uow.get_block(&block_id)?;
                    if let Some(ref b) = block {
                        let line = self.render_block_line(
                            uow,
                            b,
                            quote_prefix,
                            first_block_role.take(),
                            &mut open_levels,
                            options,
                        )?;
                        if !result.is_empty() {
                            result.push_str(&separator);
                        }
                        result.push_str(&line);
                    }
                } else {
                    // Negative: negated sub-frame ID
                    let sub_frame_id = (-entry) as EntityId;
                    if cell_frame_ids.contains(&sub_frame_id) {
                        continue;
                    }
                    let sub_frame = uow.get_frame(&sub_frame_id)?;
                    if let Some(ref sf) = sub_frame {
                        // Check if sub-frame is a table anchor
                        if let Some(table_id) = sf.table {
                            let table_md = self.render_table_djot(uow, &table_id)?;
                            let prefixed = if !quote_prefix.is_empty() {
                                prefix_lines(&table_md, quote_prefix)
                            } else {
                                table_md
                            };
                            if !result.is_empty() {
                                result.push_str(&separator);
                            }
                            result.push_str(&prefixed);
                            open_levels.clear();
                            continue;
                        }

                        // Blockquote sub-frame
                        let sub_prefix = if sf.fmt_is_blockquote == Some(true) {
                            format!("{}> ", quote_prefix)
                        } else {
                            quote_prefix.to_string()
                        };

                        let sub_text = self.render_frame_content(
                            uow,
                            sf,
                            cell_frame_ids,
                            &sub_prefix,
                            options,
                        )?;
                        if !sub_text.is_empty() {
                            if !result.is_empty() {
                                result.push_str(&separator);
                            }
                            result.push_str(&sub_text);
                        }
                        open_levels.clear();
                    }
                }
            }
        } else {
            // Fallback: iterate blocks from the Blocks relationship
            let block_ids = uow.get_frame_relationship(
                &frame.id,
                &common::direct_access::frame::FrameRelationshipField::Blocks,
            )?;

            if block_ids.is_empty() {
                return Ok(result);
            }

            let blocks_opt = uow.get_block_multi(&block_ids)?;
            let mut blocks: Vec<Block> = blocks_opt.into_iter().flatten().collect();
            // Ordered by where each block starts in the rope: the stored field lags it by
            // whatever was typed since something last wrote it.
            common::database::rope_helpers::refresh_block_positions(&mut blocks, &uow.store());
            blocks.sort_by_key(|b| b.document_position);

            for block in &blocks {
                let line = self.render_block_line(
                    uow,
                    block,
                    quote_prefix,
                    first_block_role.take(),
                    &mut open_levels,
                    options,
                )?;
                if !result.is_empty() {
                    result.push_str(&separator);
                }
                result.push_str(&line);
            }
        }

        Ok(result)
    }

    /// Render a single block into a djot line string, updating `open_levels` to
    /// what the parser will have open once it has read the block.
    ///
    /// # The items before decide, because that is how the parser reads them
    ///
    /// `open_levels` holds one entry per list nesting level open after the block
    /// just written, outermost first: the last entry is the item just written, and
    /// the others are the items it sits inside. Any block that is not a list item
    /// closes them all. Djot reads an item against those levels and nothing else,
    /// so the model's own list structure is written only as far as the re-parse
    /// will see it:
    ///
    /// * an item nests at most one level below the previous item. An indented
    ///   item with no item above it (the first block, or one after a paragraph or
    ///   a heading) is read back at the top level, and one indented two levels
    ///   past its neighbour one level down. The model can hold both (the importer
    ///   makes the first from `- a. a`, a bullet whose only content is a nested
    ///   list), so the indent is capped to what the re-parse produces.
    /// * an ordered item continues the numbering exactly when it will be read as
    ///   the same list: the level it lands on holds an ordered item with the same
    ///   style and delimiter. That item need not be the previous block, since the
    ///   parser resumes a list once a sub-list nested in it closes (`1. a`, then
    ///   `  - x`, then `2. b`). Two adjacent lists the model keeps apart are one
    ///   list to Djot, and an item after a heading starts a new one even when the
    ///   model says it continues.
    ///
    /// Each mismatch either left export short of a fixpoint (the numbers or the
    /// indents changed at the second save) or wrote numbers the reloaded list does
    /// not show.
    ///
    /// # A line break inside the block
    ///
    /// The model marks a line break by starting a new block, so a block's own text
    /// should hold none. Some can reach it all the same (text inserted or dropped with
    /// a `\n` in it), and written raw, each one started a new line of Djot that nothing
    /// guarded: a blank line ended the paragraph, and the lines after it were read back
    /// as lists, headings and quotations, nested as deep as their markers said.
    ///
    /// Each line is written as a block of its own instead, the block the reader makes
    /// of a line after a hard break: a paragraph, a heading of the same level, or an
    /// item of the same list at the same column, numbered on. Each is guarded as any
    /// block's text is, so the text comes back line for line, and the first save is
    /// already the one every later save writes. A line with nothing in it is left out:
    /// the reader keeps no block for an empty paragraph.
    ///
    /// Hard breaks would have said the same in one paragraph, but a paragraph costs the
    /// parser a call a line while an inline opener waits, and one longer than
    /// [`MAX_LEAF_LINES`](common::parser_tools::djot_depth::MAX_LEAF_LINES) is not
    /// parsed at all: it is read back as its source lines, every one showing its `\`
    /// and its escapes, which the next save kept for good. A block a line is one line
    /// long however many lines the model's block holds.
    fn render_block_line(
        &self,
        uow: &dyn ExportDjotUnitOfWorkTrait,
        block: &Block,
        quote_prefix: &str,
        frame_role: Option<&SemanticRole>,
        open_levels: &mut Vec<OpenLevel>,
        options: &DjotExportOptions,
    ) -> Result<String> {
        // Check if this is a code block
        if block.fmt_is_code_block == Some(true) {
            let block_text = block_content_via_store(block, &uow.store());
            let elements = common::format_runs_query::inline_segments_for_block(
                &uow.store(),
                block.id,
                &block_text,
            );

            // Concatenate raw text from elements, no formatting
            let mut raw_text = String::new();
            for elem in &elements {
                match &elem.content {
                    InlineContent::Text(t) => raw_text.push_str(t),
                    InlineContent::Empty => {}
                    // Neither an image nor a footnote reference has raw text to
                    // contribute to a verbatim code block.
                    InlineContent::Image { .. } | InlineContent::FootnoteRef { .. } => {}
                }
            }

            open_levels.clear();
            return Ok(djot_code_block(
                &raw_text,
                block.fmt_code_language.as_deref(),
                quote_prefix,
            ));
        }

        // Synthesize inline segments view
        let block_text = block_content_via_store(block, &uow.store());
        let elements = common::format_runs_query::inline_segments_for_block(
            &uow.store(),
            block.id,
            &block_text,
        );

        // Check if block has a list
        let list_ids = uow.get_block_relationship(
            &block.id,
            &common::direct_access::block::BlockRelationshipField::List,
        )?;
        let list = if let Some(list_id) = list_ids.first() {
            uow.get_list(list_id)?
        } else {
            None
        };

        // Build inline djot text, one entry per line of the block's text, each written
        // as a block of its own (see "A line break inside the block" above).
        let lines = lines_to_write(self.render_inline_segments(&elements, false)?);
        let separator = block_separator(quote_prefix);

        // Standalone paragraphs and headings may carry a leading `{key=value}` djot
        // block-attribute line for the optional block-style attributes; list items and
        // code blocks do not. The frame's role and the page break belong where the
        // block starts, so the blocks written for its later lines leave them out.
        let first_attrs = render_block_attrs(block, frame_role, options, true);
        let later_attrs = if lines.len() > 1 {
            render_block_attrs(block, None, options, false)
        } else {
            String::new()
        };
        let attrs_of = |i: usize| {
            if i == 0 {
                first_attrs.as_str()
            } else {
                later_attrs.as_str()
            }
        };
        let block_line = if let Some(level) = block.fmt_heading_level {
            open_levels.clear();
            // A heading's text is inline only, so it needs no block guard.
            let prefix = format!("{quote_prefix}{} ", "#".repeat(level as usize));
            lines
                .iter()
                .enumerate()
                .map(|(i, line)| {
                    let head = format!("{prefix}{}", djot_block_text(line, false));
                    prepend_block_attrs(attrs_of(i), quote_prefix, head)
                })
                .collect::<Vec<_>>()
                .join(&separator)
        } else if let Some(ref list_entity) = list {
            // One level per indent from 0, so the item may open at most the level after
            // the last one. It closes its own level and every deeper one, and takes the
            // place of the item that was open at its own.
            let indent = (list_entity.indent.max(0) as usize).min(open_levels.len());
            let mut at_this_level = open_levels.drain(indent..).next();
            // Where the parser reads it as nested in the item one level up: see
            // `OpenLevel::child_column`.
            let column = open_levels.last().map_or(0, OpenLevel::child_column);
            let indent_prefix = " ".repeat(column);
            let mut items = Vec::with_capacity(lines.len());
            for line in &lines {
                let (marker, ordered, counter) = djot_list_marker(
                    list_entity,
                    block.fmt_marker.as_ref(),
                    at_this_level.as_ref(),
                );
                // An item's content is parsed as blocks of its own, so it needs the same
                // guard as a paragraph: `- 1. not a sublist` is a nested list, `- # x` a
                // heading.
                items.push(format!(
                    "{quote_prefix}{indent_prefix}{marker} {}",
                    djot_block_text(line, true)
                ));
                at_this_level = Some(OpenLevel {
                    ordered,
                    counter,
                    column,
                    marker_width: marker.chars().count(),
                });
            }
            open_levels.extend(at_this_level);
            items.join(&separator)
        } else {
            open_levels.clear();
            // A paragraph's content sits at the start of a line; guard against
            // its leading characters being parsed as a block-construct marker.
            lines
                .iter()
                .enumerate()
                .map(|(i, line)| {
                    let para = format!("{quote_prefix}{}", djot_block_text(line, true));
                    prepend_block_attrs(attrs_of(i), quote_prefix, para)
                })
                .collect::<Vec<_>>()
                .join(&separator)
        };

        Ok(block_line)
    }

    /// Render inline segments into djot text with formatting.
    ///
    /// Marks are applied innermost→outermost so the re-parse nests identically,
    /// producing a canonical form that makes export∘import a fixpoint:
    /// verbatim → **link** → subscript → superscript → delete → insert →
    /// strong/emphasis.
    ///
    /// # The link must be innermost
    ///
    /// It used to be outermost, which meant a **superscript link** was written
    /// `[^aa^](url)` — the `^` markers inside the brackets. `[^…]` is djot's
    /// **footnote-reference** syntax, so the re-parse read it as a footnote and
    /// the link was destroyed: `^[aa](url)^` exported to `[^aa^](url)`, which
    /// re-exported to `\(url\)`. Silent, total loss of the link text, in the
    /// format a manuscript is *saved* in.
    ///
    /// Wrapping the other way (`^[aa](url)^`) is equally valid djot for the same
    /// entity state, collides with nothing, and round-trips. The other marks
    /// (`*`, `_`, `{-`, `{+`) do not collide either way, so the one order that is
    /// safe for all of them is: link first, marks around it.
    ///
    /// The price of that order is that the destination sits *inside* the marks,
    /// where a `*` in the URL of a bold link closes the bold and takes the link
    /// with it. [`djot_destination`] percent-encodes exactly those characters.
    ///
    /// # Each run is escaped against its neighbours
    ///
    /// A run's text is escaped knowing the text on either side of it in the block.
    /// Two runs can differ only in a way Djot does not write (a font size, a
    /// tooltip) and so land side by side with no markup between them: `a-` and
    /// `-b` are each harmless, and together the `--` that the re-parse turns into
    /// an en dash. See [`escape_djot_inline_in_context`].
    ///
    /// # After an image's size
    ///
    /// An image is written with its size as an attribute set, `{width=… height=…}`, and
    /// the parser reads a `{` straight after an attribute set as more attributes for the
    /// same image. A struck run shaped like `key=value` is written `{-x=5-}`, which is
    /// also a valid attribute, so the struck text disappeared into the image at the
    /// reload. [`guard_djot_attribute_continuation`] escapes the piece written there.
    ///
    /// # One entry per line
    ///
    /// The result holds one entry per line of the block's text, split at each `\n` a
    /// text run holds (see `render_block_line`), each rendered on its own, as the text
    /// of a block of its own: no markup spans two lines and no neighbour is read across
    /// one.
    fn render_inline_segments(
        &self,
        elements: &[InlineSegment],
        in_table_cell: bool,
    ) -> Result<Vec<String>> {
        split_segments_at_line_breaks(elements)
            .iter()
            .map(|line| self.render_inline_line(line, in_table_cell))
            .collect()
    }

    /// Render one line of a block's inline segments (see
    /// [`render_inline_segments`](Self::render_inline_segments)) as Djot text.
    /// `in_table_cell` says the line is written inside a table row (see
    /// [`djot_destination`]).
    fn render_inline_line(
        &self,
        elements: &[InlineSegment],
        in_table_cell: bool,
    ) -> Result<String> {
        let line = self.block_text_for_escaping(elements);
        let mut inline = String::new();
        // Whether `inline` ends with the closing fence of a code span. jotdown reads
        // the token after that fence while still in verbatim mode, so a backslash there
        // escapes nothing (`` `a`\" `` curls the quote) and a backtick there lengthens
        // the fence (two code runs side by side read back with the backticks as text).
        // An empty attribute set `{}` ends the span first and is itself invisible.
        let mut after_code_fence = false;
        // Whether `inline` ends with an image's size attributes, which the next piece
        // would continue if it opened with a valid attribute set of its own.
        let mut after_attribute_set = false;
        for (elem, span) in elements.iter().zip(&line.spans) {
            let is_code = is_code_segment(elem);
            // The size attributes of an image piece, to tell whether they still end the
            // piece once the marks are wrapped around it.
            let mut image_attributes: Option<String> = None;

            // `(lead, body, trail)`: djot emphasis-family markers (`*`, `_`,
            // `^`, `~`, `{- -}`, `{+ +}`) must not sit directly against
            // whitespace, so for non-code text we move leading/trailing spaces
            // OUTSIDE all markers. Code is verbatim (jotdown keeps spaces), so
            // it is left intact, except for whitespace next to a backtick at
            // either end, which a code span cannot hold (`split_verbatim_edge_ws`).
            let (lead, mut formatted, trail): (&str, String, &str) = match &elem.content {
                InlineContent::Text(t) if is_code => {
                    let (l, core, tr) = split_verbatim_edge_ws(t);
                    (l, djot_inline_code(core), tr)
                }
                InlineContent::Text(t) => {
                    let (l, core, tr) = split_surrounding_ws(t);
                    if core.is_empty() {
                        // Whitespace-only (or empty) run: emit verbatim, no
                        // markers (it carries no visible formatting).
                        inline.push_str(t);
                        after_code_fence &= t.is_empty();
                        after_attribute_set &= t.is_empty();
                        continue;
                    }
                    let escaped = match span {
                        Some(span) => {
                            let core_start = span.start + l.len();
                            let core_end = core_start + core.len();
                            escape_djot_inline_in_context(
                                &line.text[..core_start],
                                core,
                                &line.text[core_end..],
                            )
                        }
                        None => escape_djot(core),
                    };
                    (l, escaped, tr)
                }
                InlineContent::Image {
                    name,
                    alt,
                    width,
                    height,
                    ..
                } => {
                    if self.omit_images {
                        continue;
                    }
                    // Djot carries display size as inline attributes. Writing
                    // them keeps a resize durable across a save/reload, and
                    // round-trips through this crate's own importer.
                    //
                    // The name is a destination like a link's, and is encoded the same
                    // way (see `djot_destination`), where the importer decodes it: the
                    // name is the key a host finds the image under, not a URL whose
                    // encoded form means the same. A line break in the description
                    // would end the line the image is written on, so it is a space.
                    let alt = escape_djot(&alt.replace(['\n', '\r'], " "));
                    let mut out = format!(
                        "![{alt}]({})",
                        djot_destination(name, elem, in_table_cell, Destination::Image)
                    );
                    if *width > 0 && *height > 0 {
                        let size = format!("{{width={width} height={height}}}");
                        out.push_str(&size);
                        image_attributes = Some(size);
                    }
                    ("", out, "")
                }
                // A footnote reference is written and **done** — it does not
                // fall through into the mark-wrapping cascade below the way an
                // image deliberately does (an image can be linked; a reference
                // cannot).
                //
                // Falling through would be the superscript-link bug wearing a
                // new hat. A reference normally carries
                // `vertical_alignment: SuperScript`, because that is what draws
                // the marker in the editor — so the cascade would wrap it as
                // `^[^label]^`, marking up syntax that every djot reader
                // already renders raised, and handing the re-parse a
                // superscript containing a footnote instead of a footnote.
                InlineContent::FootnoteRef { label } => {
                    let reference = format!("[^{label}]");
                    if joins_into_markup(&inline, &reference) {
                        inline.push_str("{}");
                    }
                    inline.push_str(&reference);
                    after_code_fence = false;
                    after_attribute_set = false;
                    continue;
                }
                InlineContent::Empty => continue,
            };

            // Innermost: the link. Putting it outside the marks writes `[^aa^](url)`,
            // and `[^…]` is a footnote reference — see the note above.
            if let Some(ref href) = elem.fmt_anchor_href {
                formatted = format!(
                    "[{formatted}]({})",
                    djot_destination(href, elem, in_table_cell, Destination::Link)
                );
            }
            if elem.fmt_vertical_alignment == Some(CharVerticalAlignment::SubScript) {
                formatted = format!("~{formatted}~");
            } else if elem.fmt_vertical_alignment == Some(CharVerticalAlignment::SuperScript) {
                formatted = format!("^{formatted}^");
            }
            if elem.fmt_font_strikeout == Some(true) {
                formatted = format!("{{-{formatted}-}}");
            }
            if elem.fmt_font_underline == Some(true) {
                formatted = format!("{{+{formatted}+}}");
            }
            if elem.fmt_font_bold == Some(true) && elem.fmt_font_italic == Some(true) {
                formatted = format!("*_{formatted}_*");
            } else if elem.fmt_font_bold == Some(true) {
                formatted = format!("*{formatted}*");
            } else if elem.fmt_font_italic == Some(true) {
                formatted = format!("_{formatted}_");
            }

            if after_attribute_set && lead.is_empty() {
                formatted = guard_djot_attribute_continuation(&formatted);
            }
            let opens_with = lead.chars().chain(formatted.chars()).next();
            if (after_code_fence && matches!(opens_with, Some('\\' | '`')))
                || (lead.is_empty() && joins_into_markup(&inline, &formatted))
            {
                inline.push_str("{}");
            }
            after_code_fence = is_code && trail.is_empty() && formatted.ends_with('`');
            // Only the size itself is continued. A mark or a link wrapped around the image
            // closes after it, and after a closer the parser takes attributes from a lone
            // `{` only, which no piece opens with: text escapes it, and `{-` and `{+` are
            // read as delimiters there.
            after_attribute_set =
                trail.is_empty() && image_attributes.is_some_and(|size| formatted.ends_with(&size));
            inline.push_str(lead);
            inline.push_str(&formatted);
            inline.push_str(trail);
        }
        Ok(inline)
    }

    /// The block's text as the escaper should see it: every non-code text run in
    /// order, with a stand-in character wherever something the exporter writes as its
    /// own construct (inline code, an image, a footnote reference) separates two runs.
    /// Those constructs open and close with brackets or backticks, so they keep the
    /// runs on either side from reading as one. An image left out by `omit_images`
    /// leaves no trace, and its neighbours meet.
    fn block_text_for_escaping(&self, elements: &[InlineSegment]) -> EscapeLine {
        let mut line = EscapeLine {
            text: String::new(),
            spans: Vec::with_capacity(elements.len()),
        };
        for elem in elements {
            match &elem.content {
                InlineContent::Text(t) if !is_code_segment(elem) => {
                    let start = line.text.len();
                    line.text.push_str(t);
                    line.spans.push(Some(start..line.text.len()));
                    continue;
                }
                InlineContent::Image { .. } if self.omit_images => {}
                InlineContent::Empty => {}
                InlineContent::Text(_)
                | InlineContent::Image { .. }
                | InlineContent::FootnoteRef { .. } => line.text.push(RUN_SEPARATOR),
            }
            line.spans.push(None);
        }
        line
    }

    fn render_table_djot(
        &self,
        uow: &dyn ExportDjotUnitOfWorkTrait,
        table_id: &EntityId,
    ) -> Result<String> {
        let table = uow
            .get_table(table_id)?
            .ok_or_else(|| anyhow!("Table not found"))?;

        let cell_ids = uow.get_table_relationship(
            table_id,
            &common::direct_access::table::TableRelationshipField::Cells,
        )?;
        let cells_opt = uow.get_table_cell_multi(&cell_ids)?;
        let mut cells: Vec<TableCell> = cells_opt.into_iter().flatten().collect();
        cells.sort_by(|a, b| a.row.cmp(&b.row).then(a.column.cmp(&b.column)));

        let rows = table.rows as usize;
        let cols = table.columns as usize;

        // Build a grid of cell content strings
        let mut grid: Vec<Vec<String>> = vec![vec![String::new(); cols]; rows];

        for cell in &cells {
            let r = cell.row as usize;
            let c = cell.column as usize;
            if r >= rows || c >= cols {
                continue;
            }

            let mut cell_text = String::new();
            if let Some(cf_id) = cell.cell_frame {
                let block_ids = uow.get_frame_relationship(
                    &cf_id,
                    &common::direct_access::frame::FrameRelationshipField::Blocks,
                )?;
                let blocks_opt = uow.get_block_multi(&block_ids)?;
                let mut blocks: Vec<Block> = blocks_opt.into_iter().flatten().collect();
                // Ordered by where each block starts in the rope: the stored field lags it by
                // whatever was typed since something last wrote it.
                common::database::rope_helpers::refresh_block_positions(&mut blocks, &uow.store());
                blocks.sort_by_key(|b| b.document_position);

                // A row is one line of Djot, so a cell holds no line break: its blocks,
                // and the lines of each, are joined with a space. The spaces the parser
                // trims off a cell's two ends are kept by an empty attribute set.
                let mut parts: Vec<String> = Vec::new();
                for block in &blocks {
                    let inline_md = self.render_inline_djot(uow, block)?.join(" ");
                    if !inline_md.is_empty() {
                        parts.push(inline_md);
                    }
                }
                cell_text = keep_djot_edge_whitespace(&parts.join(" "));
            }

            grid[r][c] = cell_text;
        }

        // A row made only of cells that read as `-`, `:-` or `-:` is a separator row to
        // the parser, which sets the column alignment from it and drops it: the row's text
        // was lost, and, as the first row, the header row with it. One escaped dash keeps
        // it a row of text.
        for row in &mut grid {
            if !row.is_empty() && row.iter().all(|cell| is_separator_cell(cell)) {
                let first = &mut row[0];
                if let Some(dash) = first.find('-') {
                    first.insert(dash, '\\');
                }
            }
        }

        // Render as pipe-delimited djot table
        let mut md = String::new();

        for (r, row) in grid.iter().enumerate() {
            md.push('|');
            for cell_text in row {
                md.push(' ');
                md.push_str(cell_text);
                md.push_str(" |");
            }
            md.push('\n');

            // Add separator after header row
            if r == 0 {
                md.push('|');
                for _ in 0..cols {
                    md.push_str("---|");
                }
                md.push('\n');
            }
        }

        // Remove trailing newline
        if md.ends_with('\n') {
            md.pop();
        }

        Ok(md)
    }

    /// A table cell's block as inline Djot, one entry per line (see
    /// [`render_inline_segments`](Self::render_inline_segments)).
    fn render_inline_djot(
        &self,
        uow: &dyn ExportDjotUnitOfWorkTrait,
        block: &Block,
    ) -> Result<Vec<String>> {
        let block_text = block_content_via_store(block, &uow.store());
        let elements = common::format_runs_query::inline_segments_for_block(
            &uow.store(),
            block.id,
            &block_text,
        );

        self.render_inline_segments(&elements, true)
    }
}

/// What goes between two blocks of one frame: a blank line, carrying the
/// quotation's markers inside a quotation (`>` or `> >`, without the space
/// after the last one).
///
/// A blank line without them ends the quotation, and the next block opens
/// another one. Paragraphs came back from that the same, since the importer
/// places each block by how deeply it is quoted, but a nested list item came
/// back at the top level: the item it was nested in had been left in the
/// quotation before.
fn block_separator(quote_prefix: &str) -> String {
    if quote_prefix.is_empty() {
        "\n\n".to_string()
    } else {
        format!("\n{}\n", quote_prefix.trim_end())
    }
}

/// One list nesting level the parser has open, as written: the last item written at
/// that level. Its index in `open_levels` is its indent.
struct OpenLevel {
    /// The marker of an ordered item; `None` for a bullet or a task.
    ordered: Option<OrderedMarker>,
    /// The number written for an ordered item; unused otherwise.
    counter: i64,
    /// The column the item's marker is written at, inside any quotation markers.
    column: usize,
    /// The width of the item's marker: 1 for `-`, 2 for `1.`, 4 for `(ii)` and
    /// `100.`, 5 for a task's `- [ ]`.
    marker_width: usize,
}

impl OpenLevel {
    /// The column an item nested in this one is written at: two spaces in, or as far
    /// as the marker is wide when that is further.
    ///
    /// The parser takes up to the marker's width of indentation (counted from the
    /// line's own start) off each line it continues the item on. An item nested
    /// less deep than that keeps nothing of its indentation, which is still enough
    /// to nest it, but the item nested in *it* then lands in the same column: under
    /// `- [ ] a`, items written two and four spaces in both came back one level
    /// down, and so did those under `iii.`, `(ii)` or a hundredth item. Written at
    /// least the marker's width in, every deeper line keeps the same indentation
    /// relative to the others, so each level nests in the one above. Two spaces is
    /// the least, and what a marker one or two wide has always been given.
    fn child_column(&self) -> usize {
        self.column + self.marker_width.max(2)
    }
}

/// What makes two ordered items at one level one list to the parser: the numbering
/// style and the text around the number.
#[derive(PartialEq)]
struct OrderedMarker {
    style: ListStyle,
    prefix: String,
    suffix: String,
}

/// A block's text runs laid end to end, for escaping each run against its neighbours.
struct EscapeLine {
    /// The concatenated text, with [`RUN_SEPARATOR`] where a construct sits between runs.
    text: String,
    /// Per inline segment, in order: the byte range of its text in `text`, or `None` for
    /// a segment that is not escaped as text (code, an image, a footnote reference).
    spans: Vec<Option<std::ops::Range<usize>>>,
}

/// Stands for a construct between two runs in [`EscapeLine::text`]. Any character the
/// escaper treats as neither punctuation nor a symbol character would do.
const RUN_SEPARATOR: char = '\u{FFFC}';

/// Whether writing `next` straight after `inline` would make the two read as markup
/// that neither holds alone, which an empty attribute set `{}` between them prevents.
///
/// The text escaper cannot see these, because each pairs the end of a text run with
/// markup the exporter writes itself:
///
/// * a `!` before a link or a footnote reference opens an image, `![`. A link came
///   back as an image placeholder, taking the `!` and the link text with it, and a
///   footnote reference came back as the literal text `[^1]`.
/// * a `$` (or `$$`) before a code span's opening fence makes it inline (display)
///   math, and the `$` and the code text both disappeared. jotdown does not read it
///   so when the byte before the `$` is a backslash.
///
/// `{}` rather than a backslash, because a backslash right after a code span's
/// closing fence escapes nothing (see `render_inline_segments`), while `{}` is read
/// the same everywhere and shows nothing.
fn joins_into_markup(inline: &str, next: &str) -> bool {
    let bytes = inline.as_bytes();
    match bytes.last() {
        Some(b'!') => next.starts_with('['),
        Some(b'$') => {
            let escaped = bytes.len() >= 2 && bytes[bytes.len() - 2] == b'\\';
            next.starts_with('`') && !escaped
        }
        _ => false,
    }
}

/// Whether jotdown reads `cell`, a table cell as written, as a cell of a separator
/// row: one or more dashes, optionally opened or closed by a colon (`-`, `:-`, `-:`,
/// `:---:`). A port of the check in jotdown's table parser.
fn is_separator_cell(cell: &str) -> bool {
    let cell = cell.trim_matches(|c: char| c.is_ascii_whitespace());
    let bytes = cell.as_bytes();
    match bytes.len() {
        0 => false,
        1 => cell == "-",
        2 => matches!(cell, ":-" | "--" | "-:"),
        len => {
            matches!(bytes[0], b'-' | b':')
                && matches!(bytes[len - 1], b'-' | b':')
                && bytes[1..len - 1].iter().all(|c| *c == b'-')
        }
    }
}

/// Whether `elem` is written as inline code (verbatim, never escaped).
fn is_code_segment(elem: &InlineSegment) -> bool {
    elem.fmt_font_family.as_deref() == Some("monospace")
}

/// Prefix every line of `text` with `prefix`.
fn prefix_lines(text: &str, prefix: &str) -> String {
    text.lines()
        .map(|line| format!("{}{}", prefix, line))
        .collect::<Vec<_>>()
        .join("\n")
}

/// Render the optional block-style attributes of `block` as a djot
/// `{key=value …}` block-attribute string, honouring the export `options`.
/// Returns an empty string when the block carries none of the selected
/// attributes. Keys are the model field names so the importer reads them back
/// verbatim, making the model→djot→model round-trip a fixpoint.
///
/// `starts_the_block` is false for the block written for a line after the first of a
/// block holding line breaks (see `render_block_line`), which leaves the page break out:
/// it belongs where the block starts, and on every line it put each one on a page of
/// its own.
fn render_block_attrs(
    block: &Block,
    frame_role: Option<&SemanticRole>,
    options: &DjotExportOptions,
    starts_the_block: bool,
) -> String {
    let mut pairs: Vec<String> = Vec::new();

    // The enclosing blockquote's role, written on its first block — djot block attributes
    // are the only channel, and the importer lifts it back onto the frame. Emitted first
    // so the pair reads as what it describes before the paragraph's own styling.
    if options.semantic_role
        && let Some(role) = frame_role
    {
        let v = match role {
            SemanticRole::Epigraph => "epigraph",
        };
        pairs.push(format!("semantic_role={v}"));
    }

    if options.alignment
        && let Some(alignment) = &block.fmt_alignment
    {
        let v = match alignment {
            Alignment::Left => "left",
            Alignment::Right => "right",
            Alignment::Center => "center",
            Alignment::Justify => "justify",
        };
        pairs.push(format!("alignment={v}"));
    }
    if options.line_height
        && let Some(lh) = block.fmt_line_height
    {
        pairs.push(format!("line_height={lh}"));
    }
    if options.direction
        && let Some(direction) = &block.fmt_direction
    {
        let v = match direction {
            TextDirection::LeftToRight => "ltr",
            TextDirection::RightToLeft => "rtl",
        };
        pairs.push(format!("direction={v}"));
    }
    if options.non_breakable_lines
        && let Some(nbl) = block.fmt_non_breakable_lines
    {
        pairs.push(format!("non_breakable_lines={nbl}"));
    }
    if options.page_break_before
        && starts_the_block
        && let Some(pbb) = block.fmt_page_break_before
    {
        pairs.push(format!("page_break_before={pbb}"));
    }
    if options.background_color
        && let Some(bg) = &block.fmt_background_color
    {
        pairs.push(format!("background_color={}", djot_attr_value(bg)));
    }
    if options.top_margin
        && let Some(tm) = block.fmt_top_margin
    {
        pairs.push(format!("top_margin={tm}"));
    }
    if options.text_indent
        && let Some(ti) = block.fmt_text_indent
    {
        pairs.push(format!("text_indent={ti}"));
    }

    if pairs.is_empty() {
        String::new()
    } else {
        format!("{{{}}}", pairs.join(" "))
    }
}

/// Prepend a block-attribute line to a rendered block `body`, repeating the
/// blockquote `quote_prefix` on the attribute line. A no-op when `attr_line` is
/// empty.
fn prepend_block_attrs(attr_line: &str, quote_prefix: &str, body: String) -> String {
    if attr_line.is_empty() {
        body
    } else {
        format!("{quote_prefix}{attr_line}\n{body}")
    }
}

/// Encode an arbitrary attribute value as a double-quoted djot attribute value,
/// escaping `\` and `"` so it round-trips through jotdown's attribute parser
/// verbatim (covers colors like `#ff0000` and values containing spaces).
fn djot_attr_value(value: &str) -> String {
    let escaped = value.replace('\\', "\\\\").replace('"', "\\\"");
    format!("\"{escaped}\"")
}

/// Bullet character for an unordered/task list style (inverse of the importer's
/// `-`↔Disc / `*`↔Circle / `+`↔Square bijection).
fn djot_bullet_char(style: &ListStyle) -> &'static str {
    match style {
        ListStyle::Circle => "*",
        ListStyle::Square => "+",
        // Disc and any ordered style used as a task fallback.
        _ => "-",
    }
}

/// Render the counter token for an ordered list of the given style.
/// (Alpha is `a..z` cycling; Roman covers the common small range. Start number
/// is not modelled, so counting always begins at 1.)
fn djot_ordered_token(style: &ListStyle, n: i64) -> String {
    match style {
        ListStyle::LowerAlpha => djot_alpha(n, false),
        ListStyle::UpperAlpha => djot_alpha(n, true),
        ListStyle::LowerRoman => djot_roman(n).to_lowercase(),
        ListStyle::UpperRoman => djot_roman(n),
        // Decimal and any non-ordered fallback.
        _ => n.max(1).to_string(),
    }
}

fn djot_alpha(n: i64, upper: bool) -> String {
    let n = n.max(1);
    let base = if upper { b'A' } else { b'a' };
    // 1→a, 26→z, 27→aa, …
    let mut n = n as u64;
    let mut s = Vec::new();
    while n > 0 {
        let rem = ((n - 1) % 26) as u8;
        s.push(base + rem);
        n = (n - 1) / 26;
    }
    s.reverse();
    String::from_utf8(s).unwrap()
}

fn djot_roman(n: i64) -> String {
    let mut n = n.max(1);
    let table = [
        (1000, "M"),
        (900, "CM"),
        (500, "D"),
        (400, "CD"),
        (100, "C"),
        (90, "XC"),
        (50, "L"),
        (40, "XL"),
        (10, "X"),
        (9, "IX"),
        (5, "V"),
        (4, "IV"),
        (1, "I"),
    ];
    let mut out = String::new();
    for (value, sym) in table {
        while n >= value {
            out.push_str(sym);
            n -= value;
        }
    }
    out
}

/// Emit inline code as a backtick-fenced verbatim span, widening the fence past
/// any backtick run in the content and padding when it touches a backtick
/// (djot/CommonMark convention) so the content survives verbatim.
fn djot_inline_code(text: &str) -> String {
    let mut max_run = 0usize;
    let mut cur = 0usize;
    for c in text.chars() {
        if c == '`' {
            cur += 1;
            max_run = max_run.max(cur);
        } else {
            cur = 0;
        }
    }
    let fence = "`".repeat(max_run + 1);
    // jotdown keeps a verbatim span's spaces, so we must NOT pad in general: a
    // pad space would become part of the content and grow on every round trip.
    // Sizing the fence one wider than the longest interior backtick run is enough
    // for content with leading/trailing spaces, making `export∘import` a fixpoint.
    //
    // The exception is content that begins or ends with a backtick, which would
    // merge with the fence. One space goes between them, and jotdown drops it
    // again: it skips whitespace between the opening fence and a backtick, and
    // between a backtick and the closing fence. That same rule is why whitespace
    // the *content* holds in those two places cannot be written inside the span
    // at all; `split_verbatim_edge_ws` moves it outside first.
    let lead = if text.starts_with('`') { " " } else { "" };
    let trail = if text.ends_with('`') { " " } else { "" };
    format!("{fence}{lead}{text}{trail}{fence}")
}

/// Split off the whitespace a verbatim span cannot hold: `(lead, core, trail)`.
///
/// jotdown drops an ASCII whitespace run between the opening fence and a
/// backtick, and one between a backtick and the closing fence, so code whose text
/// opened with a space and then a backtick came back without the space. Those
/// runs are written outside the span instead, where they survive as ordinary
/// spaces, the same trade the other marks make for their edge whitespace.
fn split_verbatim_edge_ws(s: &str) -> (&str, &str, &str) {
    let is_ws = |c: char| c.is_ascii_whitespace();
    let body = s.trim_start_matches(is_ws);
    let lead_len = if body.starts_with('`') {
        s.len() - body.len()
    } else {
        0
    };
    let rest = &s[lead_len..];
    let body = rest.trim_end_matches(is_ws);
    let core_len = if body.ends_with('`') {
        body.len()
    } else {
        rest.len()
    };
    (&s[..lead_len], &rest[..core_len], &rest[core_len..])
}

/// Split off leading/trailing ASCII space/tab runs: `(lead, core, trail)`.
/// `core` is empty when the input is entirely whitespace.
fn split_surrounding_ws(s: &str) -> (&str, &str, &str) {
    let is_ws = |c: char| c == ' ' || c == '\t';
    let start = s.len() - s.trim_start_matches(is_ws).len();
    let end = s.trim_end_matches(is_ws).len();
    if end <= start {
        (s, "", "")
    } else {
        (&s[..start], &s[start..end], &s[end..])
    }
}

/// What a destination written with [`djot_destination`] names.
#[derive(Clone, Copy, PartialEq, Eq)]
enum Destination {
    /// A link's URL. An encoded character names the same resource, and the reader
    /// keeps the destination as it is written.
    Link,
    /// An image's name: the key a host finds the image under, where an encoded
    /// character is a different name. The reader decodes what the writer encodes
    /// (`decode_djot_image_source`), so a `%` that would read as one of those
    /// encodings is encoded too.
    Image,
}

/// Render a destination for `[text](dest)` or `![alt](dest)`, where `elem` is the
/// segment the link or image belongs to and `in_table_cell` says it is written in a
/// table row.
///
/// jotdown keeps a destination's source bytes as the URL (a backslash is kept, not
/// read as an escape) but still runs the inline lexer over them to find the closing
/// `)`. So a character that means something to that lexer cannot be written as is,
/// and cannot be backslash-escaped either: it is percent-encoded, which leaves the
/// same resource and reads back byte-stable from then on.
///
/// * `(` and `)` always: the first `)` ends the destination, balanced or not.
/// * `` ` `` always: it opens verbatim.
/// * `\` only as the last of an odd run of them ending the destination, which
///   would escape the closing `)`. Anywhere else the lexer may read it as an escape,
///   but the escaped character is either harmless there or encoded anyway, and the
///   bytes are kept: `%5C` is not the same link, since a URL parser reads a `\` in a
///   web or file address (`file:///C:\Users\…`) as a `/`. An earlier rule encoded
///   every `\` before punctuation or whitespace, which rewrote `C:\Users\Anna\.config`
///   at the first save.
/// * `{` and `}` always: `}` completes the closer of an underline (`+}`) or a
///   strikeout (`-}`) wrapped around the link.
/// * `<` and `>` always: not legal in a URL, and `<…>` opens an autolink.
/// * a line break always: it would end the line the destination is written on.
/// * `|` in a table cell: the row is split into cells at every `|` outside a code
///   span, a destination's included, so the link lost its cell and the row's last
///   cell its place. Elsewhere it is kept.
/// * `^` right after a `[`: `[^` opens a footnote reference, which the lexer reads to
///   the next `]` in the paragraph, past the `)` that ends the destination. With an
///   escaped `\]` in the text after the link, the link came back as literal text and
///   the words in between as the label of a footnote nobody wrote. The `[` itself is
///   kept, since it is legal in a URL's host (`http://[::1]/`).
/// * `*`, `_`, `^` and `~` only when the link is bold, italic, superscript or
///   subscript: the link is written *inside* those marks (see
///   `render_inline_segments`), so the mark's own delimiter in the URL closes the
///   mark and the re-parse shows the link as literal brackets. Elsewhere they are
///   harmless, and common in URLs (`Foo_bar`, `/~user`), so they are kept.
/// * for an image only, a `%` that the reader would take for one of these encodings
///   (see [`Destination::Image`]).
///
/// Spaces are kept: jotdown reads them back verbatim. This replaces an earlier
/// `<dest>` form, which jotdown does not support: the angle brackets became part
/// of the URL and were percent-encoded again at every save.
fn djot_destination(
    dest: &str,
    elem: &InlineSegment,
    in_table_cell: bool,
    kind: Destination,
) -> String {
    let bold = elem.fmt_font_bold == Some(true);
    let italic = elem.fmt_font_italic == Some(true);
    let sup = elem.fmt_vertical_alignment == Some(CharVerticalAlignment::SuperScript);
    let sub = elem.fmt_vertical_alignment == Some(CharVerticalAlignment::SubScript);
    // The byte offset of a backslash that would escape the closing `)`: the last of an
    // odd run ending the destination.
    let trailing_backslashes = dest.bytes().rev().take_while(|b| *b == b'\\').count();
    let escaping_backslash = (trailing_backslashes % 2 == 1).then(|| dest.len() - 1);
    let mut out = String::with_capacity(dest.len());
    let mut previous = None;
    for (at, c) in dest.char_indices() {
        let encode = match c {
            '(' | ')' | '`' | '{' | '}' | '<' | '>' | '\n' | '\r' => true,
            '\\' => escaping_backslash == Some(at),
            '|' => in_table_cell,
            '*' => bold,
            '_' => italic,
            '^' => sup || previous == Some('['),
            '~' => sub,
            '%' => kind == Destination::Image && reads_as_image_source_escape(&dest[at + 1..]),
            _ => false,
        };
        if encode {
            out.push_str(&format!("%{:02X}", u32::from(c)));
        } else {
            out.push(c);
        }
        previous = Some(c);
    }
    out
}

/// Split a block's segments at each line break a text run holds: one entry per line,
/// the break itself in neither. A block without one is borrowed whole.
///
/// A run holding line breaks is copied once, and each piece of it is that copy with the
/// piece's text: copying the whole run for every piece copied its whole text once a
/// line, and saving a block of 64,000 lines took seconds.
fn split_segments_at_line_breaks(elements: &[InlineSegment]) -> Vec<Cow<'_, [InlineSegment]>> {
    let breaks =
        |elem: &InlineSegment| matches!(&elem.content, InlineContent::Text(t) if t.contains('\n'));
    if !elements.iter().any(breaks) {
        return vec![Cow::Borrowed(elements)];
    }
    let mut lines: Vec<Cow<'_, [InlineSegment]>> = Vec::new();
    let mut current: Vec<InlineSegment> = Vec::new();
    for elem in elements {
        match &elem.content {
            InlineContent::Text(t) if t.contains('\n') => {
                let format = InlineSegment {
                    content: InlineContent::Empty,
                    ..elem.clone()
                };
                for (i, piece) in t.split('\n').enumerate() {
                    if i > 0 {
                        lines.push(Cow::Owned(std::mem::take(&mut current)));
                    }
                    if !piece.is_empty() {
                        current.push(InlineSegment {
                            content: InlineContent::Text(piece.to_string()),
                            ..format.clone()
                        });
                    }
                }
            }
            _ => current.push(elem.clone()),
        }
    }
    lines.push(Cow::Owned(current));
    lines
}

/// The lines of a block to write, one block each (see `render_block_line`): every line
/// that holds something, or, when none does, one empty line, which is how an empty
/// block has always been written.
fn lines_to_write(lines: Vec<String>) -> Vec<String> {
    let kept: Vec<String> = lines.into_iter().filter(|line| !line.is_empty()).collect();
    if kept.is_empty() {
        vec![String::new()]
    } else {
        kept
    }
}

/// One line of a block's inline text, as the text of the block it is written as: guarded
/// against reading as a block marker where it opens (`guard` is false for a heading, whose
/// text the parser reads as text whatever it opens with), and keeping the whitespace at
/// its edges (see [`keep_djot_edge_whitespace`]).
fn djot_block_text(line: &str, guard: bool) -> String {
    if guard {
        keep_djot_edge_whitespace(&guard_block_start(line))
    } else {
        keep_djot_edge_whitespace(line)
    }
}

/// The marker of a list item written after `previous`, the item the parser has open at
/// its level (if any): the marker, the ordered marker it continues a list with, and the
/// number written, which is `previous`'s plus one when the parser reads the two as one
/// list. `fmt_marker` is the block's task marker.
fn djot_list_marker(
    list: &List,
    fmt_marker: Option<&MarkerType>,
    previous: Option<&OpenLevel>,
) -> (String, Option<OrderedMarker>, i64) {
    if matches!(
        fmt_marker,
        Some(MarkerType::Checked | MarkerType::Unchecked)
    ) {
        // Task list item: `<bullet> [ ]` / `<bullet> [x]`.
        let bullet = djot_bullet_char(&list.style);
        let check = if fmt_marker == Some(&MarkerType::Checked) {
            "[x]"
        } else {
            "[ ]"
        };
        return (format!("{bullet} {check}"), None, 0);
    }
    match list.style {
        ListStyle::Decimal
        | ListStyle::LowerAlpha
        | ListStyle::UpperAlpha
        | ListStyle::LowerRoman
        | ListStyle::UpperRoman => {
            // Djot needs a delimiter after the number; default to `.` if none was
            // recorded.
            let suffix = if list.suffix.is_empty() {
                "."
            } else {
                list.suffix.as_str()
            };
            let ordered = OrderedMarker {
                style: list.style.clone(),
                prefix: list.prefix.clone(),
                suffix: suffix.to_string(),
            };
            let counter = match previous {
                Some(open) if open.ordered.as_ref() == Some(&ordered) => open.counter + 1,
                _ => 1,
            };
            let token = djot_ordered_token(&list.style, counter);
            (
                format!("{}{token}{suffix}", list.prefix),
                Some(ordered),
                counter,
            )
        }
        _ => (djot_bullet_char(&list.style).to_string(), None, 0),
    }
}

/// Write a code block of `raw_text` in `language`, inside `quote_prefix`.
///
/// * The fence is one backtick longer than the longest run of backticks the text
///   holds, and never shorter than three. A line of three backticks in the text closed
///   a fence of three early: the lines after it were read back as prose and a new,
///   unclosed block.
/// * A line of whitespace alone, or an empty one, is written after the quotation's
///   markers without the space that follows the last: the parser strips only the `>`
///   from such a line, so `> ` gave an empty line a space at every save.
/// * The language is what the parser reads back as one (see [`djot_code_language`]).
fn djot_code_block(raw_text: &str, language: Option<&str>, quote_prefix: &str) -> String {
    let fence = "`".repeat(longest_backtick_run(raw_text).max(2) + 1);
    let language = djot_code_language(language);
    let bare_prefix = quote_prefix.trim_end();
    let mut out = format!("{quote_prefix}{fence}{language}");
    for line in raw_text.split('\n') {
        out.push('\n');
        if line.chars().all(|c| c.is_ascii_whitespace()) {
            out.push_str(bare_prefix);
        } else {
            out.push_str(quote_prefix);
        }
        out.push_str(line);
    }
    out.push('\n');
    out.push_str(quote_prefix);
    out.push_str(&fence);
    out
}

/// The longest run of backticks in `text`.
fn longest_backtick_run(text: &str) -> usize {
    let mut longest = 0;
    let mut run = 0;
    for c in text.chars() {
        if c == '`' {
            run += 1;
            longest = longest.max(run);
        } else {
            run = 0;
        }
    }
    longest
}

/// The language written after a code fence: the first word of `language`.
///
/// The parser reads a fence followed by more than one word, or by a word holding a
/// backtick, as the start of an inline code span, so the block and every line of it
/// came back as one paragraph: a Markdown info string such as `rust ignore` did that.
/// A word opening with `=` makes the block raw output for that format, which the
/// reader drops with its text. Neither is written; the block keeps its text and loses
/// the rest of its language.
fn djot_code_language(language: Option<&str>) -> &str {
    let word = language
        .and_then(|l| l.split_ascii_whitespace().next())
        .unwrap_or("");
    if word.contains('`') || word.starts_with('=') {
        ""
    } else {
        word
    }
}
