// Generated by Qleany v1.4.8 from feature_use_case.tera
use crate::ExportPlainTextDto;
use anyhow::{Result, anyhow};
use common::database::QueryUnitOfWork;
use common::database::rope_helpers::{block_content_via_store, rope_flat_text_if_simple};
use common::entities::{Block, Document, Frame, Root};
use common::parser_tools::{FORM_FEED, PlainTextExportOptions};
use common::types::{EntityId, ROOT_ENTITY_ID};
use std::collections::HashMap;

/// One level of blockquote indentation in the plain-text export.
///
/// Four spaces, the plain-text convention a `.txt` manuscript uses for quoted matter
/// (Shunn sets block quotations in from both margins; only the left one survives a
/// format with no margins to speak of). Deliberately not `"> "`: that is Markdown's
/// marker, and this export is the one that promises no markup at all.
const QUOTE_INDENT: &str = "    ";

/// How many blockquote frames enclose `frame_id`, walking up `parent_frame`.
///
/// A frame whose parent chain is broken (a parent missing from the document's own frame
/// list, which should not happen) stops the walk rather than looping or failing: an
/// under-indented line is a cosmetic loss, and this export must not be the thing that
/// refuses to produce a file.
fn blockquote_depth(frame_id: EntityId, frames: &HashMap<EntityId, Frame>) -> usize {
    let mut depth = 0;
    let mut current = Some(frame_id);
    // Bounded by the frame count: a cycle would otherwise hang the export, and this runs
    // on data that has been through an importer.
    let mut guard = frames.len() + 1;
    while let Some(id) = current {
        if guard == 0 {
            break;
        }
        guard -= 1;
        let Some(frame) = frames.get(&id) else { break };
        if frame.fmt_is_blockquote == Some(true) {
            depth += 1;
        }
        current = frame.parent_frame;
    }
    depth
}

/// Indent every non-empty line of `text` by `depth` levels.
///
/// Blank lines are left bare on purpose — indenting one would emit trailing whitespace,
/// which is invisible in the editor, survives into the exported file, and is exactly the
/// kind of thing a diff of two exports trips over.
fn indent_quoted(text: &str, depth: usize) -> String {
    let prefix = QUOTE_INDENT.repeat(depth);
    text.split('\n')
        .map(|line| {
            if line.trim().is_empty() {
                line.to_string()
            } else {
                format!("{prefix}{line}")
            }
        })
        .collect::<Vec<String>>()
        .join("\n")
}

pub trait ExportPlainTextUnitOfWorkFactoryTrait: Send + Sync {
    fn create(&self) -> Box<dyn ExportPlainTextUnitOfWorkTrait>;
}

#[macros::uow_action(entity = "Root", action = "GetRO")]
#[macros::uow_action(entity = "Root", action = "GetRelationshipRO")]
#[macros::uow_action(entity = "Document", action = "GetRO")]
#[macros::uow_action(entity = "Document", action = "GetRelationshipRO")]
#[macros::uow_action(entity = "Frame", action = "GetRO")]
#[macros::uow_action(entity = "Frame", action = "GetRelationshipRO")]
#[macros::uow_action(entity = "Block", action = "GetMultiRO")]
pub trait ExportPlainTextUnitOfWorkTrait: QueryUnitOfWork {}

/// Drop inline-image sentinels from plain-text output.
///
/// An image occupies one `U+FFFC` OBJECT REPLACEMENT CHARACTER in the document
/// text. Plain text has no way to represent a picture, and emitting the raw
/// sentinel put an unrenderable box in the writer's `.txt` — so the image is
/// omitted rather than transliterated. Its alt text is deliberately *not*
/// substituted: alt describes the image for a reader who cannot see it, and
/// silently promoting it to prose would put words in the manuscript that the
/// writer never typed.
fn strip_image_sentinels(text: &str) -> String {
    if text.contains('\u{FFFC}') {
        text.replace('\u{FFFC}', "")
    } else {
        text.to_string()
    }
}

pub struct ExportPlainTextUseCase {
    uow_factory: Box<dyn ExportPlainTextUnitOfWorkFactoryTrait>,
}

impl ExportPlainTextUseCase {
    pub fn new(uow_factory: Box<dyn ExportPlainTextUnitOfWorkFactoryTrait>) -> Self {
        ExportPlainTextUseCase { uow_factory }
    }

    /// Every option is opt-in, and that is not mere caution. `to_plain_text()` is pinned
    /// character-for-character to the document's own addressable text (bar table anchors),
    /// which is what `find_all` and `replace_text` compute offsets against; indenting a
    /// quote — or inserting a form feed — shifts every offset after it and silently
    /// desynchronises search from the document.
    /// `plain_text_order_tests::the_human_view_is_the_addressable_view_minus_its_anchors`
    /// is the test that says so. Presentation is a *file export* concern, so only the
    /// caller writing a `.txt` file asks for it.
    pub fn execute(&mut self, options: PlainTextExportOptions) -> Result<ExportPlainTextDto> {
        let PlainTextExportOptions {
            quote_indent,
            page_breaks,
        } = options;
        let uow = self.uow_factory.create();
        uow.begin_transaction()?;

        // Step 1: Get Root (id=1) and its Document via relationship
        let root = uow
            .get_root(&ROOT_ENTITY_ID)?
            .ok_or_else(|| anyhow!("Root entity not found"))?;

        let doc_ids = uow.get_root_relationship(
            &root.id,
            &common::direct_access::root::RootRelationshipField::Document,
        )?;
        let doc_id = *doc_ids
            .first()
            .ok_or_else(|| anyhow!("Root has no associated Document"))?;

        // Step 2: Get all Frame IDs from Document.Frames relationship
        let frame_ids = uow.get_document_relationship(
            &doc_id,
            &common::direct_access::document::DocumentRelationshipField::Frames,
        )?;

        let store = uow.store();

        // Fast path: flat single-frame document with no tables has its
        // entire plain-text representation already laid out in rope
        // byte order. One allocation replaces the per-block walk.
        if !page_breaks && let Some(plain_text) = rope_flat_text_if_simple(&store, frame_ids.len())
        {
            uow.end_transaction()?;
            return Ok(ExportPlainTextDto {
                plain_text: strip_image_sentinels(&plain_text),
            });
        }

        // Slow path: tables or multi-frame documents. Cell content and a blockquote's prose
        // live in their own Frames, so the whole document's blocks have to be gathered and
        // put back into reading order.
        //
        // Pool EVERY frame's blocks first, then sort ONCE, GLOBALLY, by `document_position`.
        //
        // This used to sort each frame's blocks against only *their own frame's* siblings and
        // then concatenate the frames in the order `Document.Frames` hands them back — which
        // is frame-CREATION order (the root frame is created up front; a blockquote's frame
        // when the quote is opened, a table's cell frames when the table is reached). That
        // silently assumed creation order equals document order, and it is false the instant a
        // sub-frame's content precedes sibling content in the parent's flow. `"> a0\n\na"`
        // exported as `"a\na0"`: every blockquote's prose was hoisted to the END of the
        // document. The CLI's `cat`/`convert` wrote that straight to stdout.
        //
        // A global sort is correct because `document_position` is a single counter over the
        // WHOLE parse — declared once, outside the frame-stack machinery, and advanced for
        // every block regardless of which frame it lands in (`import_djot_uc`). It is a
        // globally comparable reading-order key ACROSS frame boundaries, not a per-frame one.
        // This is exactly what `find_all` already does to build the text it searches, and why
        // search and this export used to disagree about where a blockquote sat.
        // Frames are also what tells a quoted block from an ordinary one: a blockquote's
        // prose lives in its own Frame, flagged `fmt_is_blockquote`. Nothing below the
        // frame layer records it, so the depth has to be resolved here, before the blocks
        // are pooled and the frame they came from is forgotten.
        let mut frames_by_id: HashMap<EntityId, Frame> = HashMap::new();
        if quote_indent {
            for frame_id in &frame_ids {
                if let Some(frame) = uow.get_frame(frame_id)? {
                    frames_by_id.insert(*frame_id, frame);
                }
            }
        }

        let mut all_block_ids: Vec<EntityId> = Vec::new();
        let mut quote_depth: HashMap<EntityId, usize> = HashMap::new();
        for frame_id in &frame_ids {
            let depth = if quote_indent {
                blockquote_depth(*frame_id, &frames_by_id)
            } else {
                0
            };
            for block_id in uow.get_frame_relationship(
                frame_id,
                &common::direct_access::frame::FrameRelationshipField::Blocks,
            )? {
                if depth > 0 {
                    quote_depth.insert(block_id, depth);
                }
                all_block_ids.push(block_id);
            }
        }

        let mut blocks: Vec<Block> = uow
            .get_block_multi(&all_block_ids)?
            .into_iter()
            .flatten()
            .collect();
        blocks.sort_by_key(|b| b.document_position);

        let plain_text = blocks
            .iter()
            .map(|block| {
                let text = strip_image_sentinels(&block_content_via_store(block, &store));
                let text = match quote_depth.get(&block.id) {
                    Some(&depth) => indent_quoted(&text, depth),
                    None => text,
                };
                // The form feed leads its block, on its own — that is what a page break
                // is in a text file, and putting it inside the line would make it part
                // of the first word.
                if page_breaks && block.fmt_page_break_before == Some(true) {
                    format!("{FORM_FEED}{text}")
                } else {
                    text
                }
            })
            .collect::<Vec<String>>()
            .join("\n");

        uow.end_transaction()?;

        Ok(ExportPlainTextDto { plain_text })
    }
}
