// Generated by Qleany v1.4.8 from feature_use_case.tera
use crate::ImportHtmlDto;
use crate::ImportHtmlResultDto;
use anyhow::{Result, anyhow};
use common::database::CommandUnitOfWork;
use common::database::rope_helpers::{
    rope_append_block, rope_append_table_anchor, rope_insert_block_boundary, rope_reset,
};
use common::direct_access::document::DocumentRelationshipField;
use common::direct_access::frame::FrameRelationshipField;
use common::direct_access::table::TableRelationshipField;
use common::entities::{
    Block, Document, Frame, FramePosition, List, Resource, Root, Table, TableCell,
};

use common::long_operation::LongOperation;
use common::parser_tools::content_parser::{
    ParsedElement, ParsedInline, format_runs_from_spans, parse_html_elements,
};
use common::parser_tools::list_grouper::ListGrouper;
use common::types::{EntityId, ROOT_ENTITY_ID};
use std::sync::Arc;

pub trait ImportHtmlUnitOfWorkFactoryTrait: Send + Sync {
    fn create(&self) -> Box<dyn ImportHtmlUnitOfWorkTrait>;
}

#[macros::uow_action(entity = "Root", action = "Get", thread_safe = true)]
#[macros::uow_action(entity = "Root", action = "GetRelationship", thread_safe = true)]
#[macros::uow_action(entity = "Document", action = "Get", thread_safe = true)]
#[macros::uow_action(entity = "Document", action = "Update", thread_safe = true)]
#[macros::uow_action(entity = "Document", action = "GetRelationship", thread_safe = true)]
#[macros::uow_action(entity = "Document", action = "SetRelationship", thread_safe = true)]
#[macros::uow_action(entity = "Frame", action = "Get", thread_safe = true)]
#[macros::uow_action(entity = "Frame", action = "CreateOrphan", thread_safe = true)]
#[macros::uow_action(entity = "Frame", action = "Update", thread_safe = true)]
#[macros::uow_action(
    entity = "Frame",
    action = "UpdateWithRelationships",
    thread_safe = true
)]
#[macros::uow_action(entity = "Frame", action = "RemoveMulti", thread_safe = true)]
#[macros::uow_action(entity = "Table", action = "RemoveMulti", thread_safe = true)]
#[macros::uow_action(entity = "List", action = "RemoveMulti", thread_safe = true)]
#[macros::uow_action(entity = "Frame", action = "GetRelationship", thread_safe = true)]
#[macros::uow_action(entity = "Frame", action = "SetRelationship", thread_safe = true)]
#[macros::uow_action(entity = "Block", action = "Create", thread_safe = true)]
#[macros::uow_action(entity = "Block", action = "CreateOrphan", thread_safe = true)]
#[macros::uow_action(entity = "Block", action = "SetRelationship", thread_safe = true)]
#[macros::uow_action(entity = "List", action = "CreateOrphan", thread_safe = true)]
#[macros::uow_action(entity = "Resource", action = "Create", thread_safe = true)]
#[macros::uow_action(entity = "Table", action = "CreateOrphan", thread_safe = true)]
#[macros::uow_action(entity = "Table", action = "SetRelationship", thread_safe = true)]
#[macros::uow_action(entity = "TableCell", action = "CreateOrphan", thread_safe = true)]
pub trait ImportHtmlUnitOfWorkTrait: CommandUnitOfWork + Send + Sync {}

pub struct ImportHtmlUseCase {
    uow_factory: Box<dyn ImportHtmlUnitOfWorkFactoryTrait>,
    dto: ImportHtmlDto,
}

struct FrameState {
    frame_id: EntityId,
    child_order: Vec<i64>,
    /// The frame's `blocks`, in creation order, written to it once when it
    /// closes. See [`OrphanedChildren`].
    blocks: Vec<EntityId>,
}

/// What the walk creates without an owner, in creation order, until each owner
/// receives its whole list in one write.
///
/// Creating a child *with* its owner appends it to the owner's list, and that
/// append rewrites the entire list, fetches every entity it names to validate
/// it, and announces the entire list in an event. One append per paragraph made
/// loading N paragraphs cost N(N+1)/2 of those: a novel kept in one document
/// took seconds to open. Ids are handed out in the same order either way, so
/// the document stored at the end is the same.
#[derive(Default)]
struct OrphanedChildren {
    /// Every frame the import creates: the document's `frames`.
    frames: Vec<EntityId>,
    /// The document's new `lists`.
    lists: Vec<EntityId>,
    /// The document's new `tables`.
    tables: Vec<EntityId>,
}

impl OrphanedChildren {
    /// Give the document its new frames, lists and tables, one write each. The
    /// frames, tables and lists it held before were all removed first, so each list
    /// written is exactly what the import created.
    fn attach(self, uow: &mut Box<dyn ImportHtmlUnitOfWorkTrait>, doc_id: EntityId) -> Result<()> {
        for (field, children) in [
            (DocumentRelationshipField::Frames, self.frames),
            (DocumentRelationshipField::Lists, self.lists),
            (DocumentRelationshipField::Tables, self.tables),
        ] {
            if children.is_empty() {
                continue;
            }
            let mut ids = uow.get_document_relationship(&doc_id, &field)?;
            ids.extend(children);
            uow.set_document_relationship(&doc_id, &field, &ids)?;
        }
        Ok(())
    }
}

/// Give a frame the blocks created for it, in one write.
fn attach_blocks(
    uow: &mut Box<dyn ImportHtmlUnitOfWorkTrait>,
    frame_id: EntityId,
    blocks: &[EntityId],
) -> Result<()> {
    if blocks.is_empty() {
        return Ok(());
    }
    uow.set_frame_relationship(&frame_id, &FrameRelationshipField::Blocks, blocks)
}

/// Advance the blockquote frame stack to match `target_depth`, finalising
/// frames that close (writing back their `blocks` and `child_order`) and
/// creating new blockquote sub-frames as depth increases. Resets
/// `list_grouper` on every frame boundary so lists never group across
/// blockquote boundaries.
///
/// Touches only Frame entities — never the rope — so rope mirroring and
/// `document_position` bookkeeping in the caller are unaffected.
fn transition_bq_depth(
    uow: &mut Box<dyn ImportHtmlUnitOfWorkTrait>,
    orphans: &mut OrphanedChildren,
    frame_stack: &mut Vec<FrameState>,
    current_bq_depth: &mut u32,
    target_depth: u32,
    opens: u32,
    list_grouper: &mut ListGrouper,
) -> Result<()> {
    // Close blockquote frames if depth decreased, and the innermost `opens` of those still
    // open when as many quotations open at the next element: two quotations one after the
    // other are two frames, not one.
    let kept_depth = target_depth.saturating_sub(opens);
    while *current_bq_depth > kept_depth && frame_stack.len() > 1 {
        let finished = frame_stack.pop().unwrap();
        attach_blocks(uow, finished.frame_id, &finished.blocks)?;
        let mut frame_entity = uow
            .get_frame(&finished.frame_id)?
            .ok_or_else(|| anyhow!("Blockquote frame not found"))?;
        frame_entity.child_order = finished.child_order;
        uow.update_frame(&frame_entity)?;
        *current_bq_depth -= 1;
        list_grouper.reset();
    }

    // Open blockquote frames if depth increased
    while *current_bq_depth < target_depth {
        let parent_frame_id = frame_stack.last().unwrap().frame_id;
        let bq_frame = Frame {
            fmt_is_blockquote: Some(true),
            fmt_position: Some(FramePosition::InFlow),
            parent_frame: Some(parent_frame_id),
            ..Frame::default()
        };
        let created_bq = uow.create_orphan_frame(&bq_frame)?;
        orphans.frames.push(created_bq.id);
        frame_stack
            .last_mut()
            .unwrap()
            .child_order
            .push(-(created_bq.id as i64));
        frame_stack.push(FrameState {
            frame_id: created_bq.id,
            child_order: Vec::new(),
            blocks: Vec::new(),
        });
        *current_bq_depth += 1;
        list_grouper.reset();
    }

    Ok(())
}

impl ImportHtmlUseCase {
    pub fn new(
        uow_factory: Box<dyn ImportHtmlUnitOfWorkFactoryTrait>,
        dto: &ImportHtmlDto,
    ) -> Self {
        ImportHtmlUseCase {
            uow_factory,
            dto: dto.clone(),
        }
    }
}

impl LongOperation for ImportHtmlUseCase {
    type Output = ImportHtmlResultDto;

    fn execute(
        &self,
        progress_callback: Box<dyn Fn(common::long_operation::OperationProgress) + Send>,
        cancel_flag: Arc<std::sync::atomic::AtomicBool>,
    ) -> Result<Self::Output> {
        use std::sync::atomic::Ordering;

        progress_callback(common::long_operation::OperationProgress::new(
            0.0,
            Some("Starting HTML import...".to_string()),
        ));

        // Parse HTML
        let parsed_elements = parse_html_elements(&self.dto.html_text);

        progress_callback(common::long_operation::OperationProgress::new(
            10.0,
            Some("Parsed HTML, building document...".to_string()),
        ));

        let mut uow = self.uow_factory.create();
        uow.begin_transaction()?;

        // Step 1: Get Root and Document
        let root = uow
            .get_root(&ROOT_ENTITY_ID)?
            .ok_or_else(|| anyhow!("Root entity not found"))?;

        let doc_ids = uow.get_root_relationship(
            &root.id,
            &common::direct_access::root::RootRelationshipField::Document,
        )?;
        let doc_id = *doc_ids
            .first()
            .ok_or_else(|| anyhow!("Root has no associated Document"))?;

        // Step 2: Remove existing frames, in one call: each single removal
        // rescans every remaining frame, so one at a time is quadratic in the
        // frames replaced.
        let frame_ids =
            uow.get_document_relationship(&doc_id, &DocumentRelationshipField::Frames)?;
        uow.remove_frame_multi(&frame_ids)?;
        // The replaced content's tables (their cells with them) and lists go too:
        // see the Djot importer.
        let table_ids =
            uow.get_document_relationship(&doc_id, &DocumentRelationshipField::Tables)?;
        uow.remove_table_multi(&table_ids)?;
        let list_ids = uow.get_document_relationship(&doc_id, &DocumentRelationshipField::Lists)?;
        uow.remove_list_multi(&list_ids)?;

        if cancel_flag.load(Ordering::Relaxed) {
            uow.rollback()?;
            return Err(anyhow!("Operation was cancelled"));
        }

        progress_callback(common::long_operation::OperationProgress::new(
            20.0,
            Some("Creating new document structure...".to_string()),
        ));

        // Step 3: Create root frame
        let mut orphans = OrphanedChildren::default();
        let new_frame = Frame::default();
        let created_frame = uow.create_orphan_frame(&new_frame)?;
        orphans.frames.push(created_frame.id);

        // Importers replace the entire document — reset the rope+
        // block_offsets. No-op under default backend.
        rope_reset(&uow.store());

        // Step 4: Create blocks with format runs and image anchors
        // Track blockquote frame stack
        let total_elements = parsed_elements.len();
        let mut total_chars: i64 = 0;
        let mut total_block_count: i64 = 0;
        let mut document_position: i64 = 0;

        let mut frame_stack: Vec<FrameState> = vec![FrameState {
            frame_id: created_frame.id,
            child_order: Vec::new(),
            blocks: Vec::new(),
        }];
        let mut current_bq_depth: u32 = 0;
        let mut list_grouper = ListGrouper::new();
        // Same intent as in import_markdown_uc: rope inter-block
        // boundaries go between main-flow blocks, not before the
        // first and not for table-cell blocks (deferred to step 5.5).
        let mut emitted_any_main_block = false;

        for (i, parsed_element) in parsed_elements.iter().enumerate() {
            if cancel_flag.load(Ordering::Relaxed) {
                uow.rollback()?;
                return Err(anyhow!("Operation was cancelled"));
            }

            match parsed_element {
                // `parse_html_elements` has no footnote syntax to recognise (HTML has
                // none of its own — `[^label]`/`[^label]:` are a Markdown/Djot
                // convention), so it never emits this variant. Dropping it here is
                // therefore unreachable today, and stated rather than assumed. Markdown
                // and Djot both build a detached `footnote_label` frame instead — see
                // `import_markdown_uc`/`import_djot_uc`.
                ParsedElement::FootnoteDefinition { .. } => {}
                ParsedElement::Block(parsed_block) => {
                    transition_bq_depth(
                        &mut uow,
                        &mut orphans,
                        &mut frame_stack,
                        &mut current_bq_depth,
                        parsed_block.blockquote_depth,
                        parsed_block.blockquote_opens,
                        &mut list_grouper,
                    )?;

                    let ParsedInline {
                        plain_text,
                        runs: format_runs,
                        images: block_images,
                        footnote_refs: block_footnote_refs,
                    } = format_runs_from_spans(&parsed_block.spans, parsed_block.is_code_block);
                    let line_len = plain_text.chars().count() as i64;

                    // The current (possibly blockquote) frame receives the
                    // block when it closes.
                    let block = Block {
                        document_position,
                        fmt_heading_level: parsed_block.heading_level,
                        fmt_line_height: parsed_block.line_height,
                        fmt_non_breakable_lines: parsed_block.non_breakable_lines,
                        fmt_direction: parsed_block.direction.clone(),
                        fmt_background_color: parsed_block.background_color.clone(),
                        fmt_is_code_block: if parsed_block.is_code_block {
                            Some(true)
                        } else {
                            None
                        },
                        fmt_code_language: parsed_block.code_language.clone(),
                        ..Block::default()
                    };

                    let created_block = uow.create_orphan_block(&block)?;

                    // Mirror into the global rope. Inter-block `\n`
                    // before every block after the first.
                    if emitted_any_main_block {
                        rope_insert_block_boundary(&uow.store());
                    }
                    rope_append_block(&uow.store(), created_block.id, &plain_text);
                    emitted_any_main_block = true;

                    // Write format_runs directly; block_images stays empty for
                    // HTML import (parser does not surface inline images today).
                    {
                        let store = uow.store();
                        let mut runs_map = store.format_runs.write();
                        if !format_runs.is_empty() {
                            runs_map.insert(created_block.id, format_runs);
                        } else {
                            runs_map.remove(&created_block.id);
                        }
                        // Image anchors travel with the runs: both index into the same
                        // block text, which already carries each image's U+FFFC sentinel.
                        let mut images_map = store.block_images.write();
                        if !block_images.is_empty() {
                            images_map.insert(created_block.id, block_images);
                        } else {
                            images_map.remove(&created_block.id);
                        }
                        // Footnote references index into the same block text.
                        let mut notes_map = store.block_footnote_refs.write();
                        if !block_footnote_refs.is_empty() {
                            notes_map.insert(created_block.id, block_footnote_refs);
                        } else {
                            notes_map.remove(&created_block.id);
                        }
                    }

                    // Handle list items
                    if let Some(ref list_style) = parsed_block.list_style {
                        let list_id = if let Some(existing_id) = list_grouper.try_reuse_list(
                            list_style,
                            parsed_block.list_indent,
                            "",
                            "",
                            parsed_block.list_start,
                        ) {
                            existing_id
                        } else {
                            let list = List {
                                style: list_style.clone(),
                                indent: parsed_block.list_indent as i64,
                                start: parsed_block.list_start,
                                ..List::default()
                            };
                            let created_list = uow.create_orphan_list(&list)?;
                            orphans.lists.push(created_list.id);
                            list_grouper.register_list(
                                created_list.id,
                                list_style.clone(),
                                parsed_block.list_indent,
                                String::new(),
                                String::new(),
                                parsed_block.list_start,
                            );
                            created_list.id
                        };

                        uow.set_block_relationship(
                            &created_block.id,
                            &common::direct_access::block::BlockRelationshipField::List,
                            &[list_id],
                        )?;
                    } else {
                        list_grouper.reset();
                    }

                    let current_frame = frame_stack.last_mut().unwrap();
                    current_frame.child_order.push(created_block.id as i64);
                    current_frame.blocks.push(created_block.id);
                    total_chars += line_len;
                    total_block_count += 1;

                    document_position += line_len;
                    if i < total_elements - 1 {
                        document_position += 1;
                    }
                }

                ParsedElement::Table(parsed_table) => {
                    // Synchronise the blockquote frame stack with the table's
                    // depth so a table inside (or right after) a blockquote
                    // lands in the correct frame.
                    transition_bq_depth(
                        &mut uow,
                        &mut orphans,
                        &mut frame_stack,
                        &mut current_bq_depth,
                        parsed_table.blockquote_depth,
                        parsed_table.blockquote_opens,
                        &mut list_grouper,
                    )?;

                    // A table always interrupts a list, regardless of depth.
                    list_grouper.reset();
                    let num_rows = parsed_table.rows.len() as i64;
                    let num_cols = parsed_table.column_count() as i64;
                    if num_rows == 0 || num_cols == 0 {
                        continue;
                    }

                    // 1. Create Table entity (owned by Document)
                    let table = Table {
                        rows: num_rows,
                        columns: num_cols,
                        column_widths: vec![],
                        ..Table::default()
                    };
                    let created_table = uow.create_orphan_table(&table)?;
                    orphans.tables.push(created_table.id);

                    // 1b. Mirror the table-anchor sentinel into the
                    // global rope. Appended at the end (the importer
                    // processes elements linearly). The boundary comes
                    // from the same positional flag every block uses —
                    // see the note on `rope_append_table_anchor`.
                    rope_append_table_anchor(
                        &uow.store(),
                        created_table.id,
                        emitted_any_main_block,
                    );

                    // 2. Create cell frames with content + TableCell entities
                    let current_frame_id = frame_stack.last().unwrap().frame_id;
                    let total_cells = num_rows * num_cols;
                    let mut cell_count: i64 = 0;
                    let mut created_cell_frame_ids: Vec<EntityId> = Vec::new();
                    // The table's `cells`, written to it in one go below.
                    let mut created_cell_ids: Vec<EntityId> = Vec::new();

                    for (r, row) in parsed_table.rows.iter().enumerate() {
                        // A row shorter than the widest is completed with empty cells.
                        for c in 0..num_cols as usize {
                            let spans = row.get(c).map_or(&[][..], |cell| cell.spans.as_slice());
                            let cell_frame = Frame::default();
                            let created_cell_frame = uow.create_orphan_frame(&cell_frame)?;
                            orphans.frames.push(created_cell_frame.id);
                            created_cell_frame_ids.push(created_cell_frame.id);

                            let ParsedInline {
                                plain_text,
                                runs: format_runs,
                                images: block_images,
                                footnote_refs: block_footnote_refs,
                            } = format_runs_from_spans(spans, false);

                            let block = Block {
                                document_position,
                                ..Block::default()
                            };
                            let created_block =
                                uow.create_block(&block, created_cell_frame.id, -1)?;

                            {
                                let store = uow.store();
                                let mut runs_map = store.format_runs.write();
                                if !format_runs.is_empty() {
                                    runs_map.insert(created_block.id, format_runs);
                                } else {
                                    runs_map.remove(&created_block.id);
                                }
                                // Image anchors travel with the runs: both index into the same
                                // block text, which already carries each image's U+FFFC sentinel.
                                let mut images_map = store.block_images.write();
                                if !block_images.is_empty() {
                                    images_map.insert(created_block.id, block_images);
                                } else {
                                    images_map.remove(&created_block.id);
                                }
                                // Footnote references index into the same block text.
                                let mut notes_map = store.block_footnote_refs.write();
                                if !block_footnote_refs.is_empty() {
                                    notes_map.insert(created_block.id, block_footnote_refs);
                                } else {
                                    notes_map.remove(&created_block.id);
                                }
                            }

                            // Mirror the cell block into the global
                            // rope: insert a `\n` boundary, then the
                            // cell's content.
                            rope_insert_block_boundary(&uow.store());
                            rope_append_block(&uow.store(), created_block.id, &plain_text);

                            let mut updated_cell_frame = created_cell_frame.clone();
                            updated_cell_frame.child_order = vec![created_block.id as i64];
                            uow.update_frame(&updated_cell_frame)?;

                            let table_cell = TableCell {
                                row: r as i64,
                                column: c as i64,
                                row_span: 1,
                                column_span: 1,
                                cell_frame: Some(created_cell_frame.id),
                                ..TableCell::default()
                            };
                            let created_cell = uow.create_orphan_table_cell(&table_cell)?;
                            created_cell_ids.push(created_cell.id);

                            let text_length = plain_text.chars().count() as i64;
                            total_chars += text_length;
                            total_block_count += 1;
                            cell_count += 1;
                            document_position += text_length;
                            if cell_count < total_cells {
                                document_position += 1;
                            }
                        }
                    }

                    uow.set_table_relationship(
                        &created_table.id,
                        &TableRelationshipField::Cells,
                        &created_cell_ids,
                    )?;

                    // 3. Create anchor frame (links table to the flow)
                    let anchor_frame = Frame {
                        parent_frame: Some(current_frame_id),
                        table: Some(created_table.id),
                        ..Frame::default()
                    };
                    let created_anchor = uow.create_orphan_frame(&anchor_frame)?;
                    orphans.frames.push(created_anchor.id);

                    // Backfill each cell frame's `parent_frame` to point at
                    // the anchor frame. Cell frames are created before the
                    // anchor (we don't know the anchor id yet), so this
                    // can't be set at creation time. Without this, walking
                    // up from a cell to find its containing table fails —
                    // breaking `insert_table_uc`'s "is the cursor inside an
                    // existing table?" check.
                    for cell_frame_id in &created_cell_frame_ids {
                        if let Some(cf) = uow.get_frame(cell_frame_id)? {
                            let mut updated = cf;
                            updated.parent_frame = Some(created_anchor.id);
                            // `update_frame` is scalar-only and preserves
                            // the existing parent_frame to guard against
                            // stale-entity writes; use the relationship-
                            // aware variant so this write actually lands.
                            uow.update_frame_with_relationships(&updated)?;
                        }
                    }

                    frame_stack
                        .last_mut()
                        .unwrap()
                        .child_order
                        .push(-(created_anchor.id as i64));

                    // Tables put content in the rope (the anchor
                    // sentinel + cell blocks) — any subsequent
                    // main-flow block must be preceded by a `\n`
                    // boundary, same as after a Block.
                    emitted_any_main_block = true;

                    if i < total_elements - 1 {
                        document_position += 1;
                    }
                }
            }

            if i % 10 == 0 {
                let pct = 20.0 + (i as f32 / total_elements as f32) * 70.0;
                progress_callback(common::long_operation::OperationProgress::new(
                    pct,
                    Some(format!("Processing element {}/{}", i + 1, total_elements)),
                ));
            }
        }

        // Close any remaining open blockquote frames
        while frame_stack.len() > 1 {
            let finished = frame_stack.pop().unwrap();
            attach_blocks(&mut uow, finished.frame_id, &finished.blocks)?;
            let mut frame_entity = uow
                .get_frame(&finished.frame_id)?
                .ok_or_else(|| anyhow!("Blockquote frame not found"))?;
            frame_entity.child_order = finished.child_order;
            uow.update_frame(&frame_entity)?;
        }

        // Step 5: Update root frame blocks and child_order
        let root_state = frame_stack.pop().unwrap();
        attach_blocks(&mut uow, root_state.frame_id, &root_state.blocks)?;
        let mut updated_frame = uow
            .get_frame(&root_state.frame_id)?
            .ok_or_else(|| anyhow!("Created frame not found"))?;
        updated_frame.child_order = root_state.child_order;
        uow.update_frame(&updated_frame)?;

        // Every frame, list and table the walk created goes to the document.
        orphans.attach(&mut uow, doc_id)?;

        // Step 6: Update document stats
        let mut updated_doc = uow
            .get_document(&doc_id)?
            .ok_or_else(|| anyhow!("Document not found after import"))?;
        updated_doc.character_count = total_chars;
        updated_doc.block_count = total_block_count;
        uow.update_document(&updated_doc)?;

        if cancel_flag.load(Ordering::Relaxed) {
            uow.rollback()?;
            return Err(anyhow!("Operation was cancelled"));
        }

        // Plan §1.6 Frame.byte_range maintenance happens in
        // Transaction::commit.
        uow.commit()?;

        progress_callback(common::long_operation::OperationProgress::new(
            100.0,
            Some("completed".to_string()),
        ));

        Ok(ImportHtmlResultDto {
            block_count: total_block_count,
        })
    }
}
