// Generated by Qleany v1.4.8 from feature_use_case.tera
use crate::ImportMarkdownDto;
use crate::ImportMarkdownResultDto;
use anyhow::{Result, anyhow};
use common::database::CommandUnitOfWork;
use common::database::rope_helpers::{
    rope_append_block, rope_append_table_anchor, rope_insert_block_boundary, rope_reset,
};
use common::direct_access::document::DocumentRelationshipField;
use common::direct_access::frame::FrameRelationshipField;
use common::direct_access::table::TableRelationshipField;
use common::entities::{Block, Document, Frame, FramePosition, List, Root, Table, TableCell};

use common::long_operation::LongOperation;
use common::parser_tools::content_parser::{
    ParsedBlock, ParsedElement, ParsedInline, format_runs_from_spans, parse_markdown,
};
use common::parser_tools::list_grouper::ListGrouper;
use common::types::{EntityId, ROOT_ENTITY_ID};
use std::sync::Arc;

pub trait ImportMarkdownUnitOfWorkFactoryTrait: Send + Sync {
    fn create(&self) -> Box<dyn ImportMarkdownUnitOfWorkTrait>;
}

#[macros::uow_action(entity = "Root", action = "Get", thread_safe = true)]
#[macros::uow_action(entity = "Root", action = "GetRelationship", thread_safe = true)]
#[macros::uow_action(entity = "Document", action = "Get", thread_safe = true)]
#[macros::uow_action(entity = "Document", action = "Update", thread_safe = true)]
#[macros::uow_action(entity = "Document", action = "GetRelationship", thread_safe = true)]
#[macros::uow_action(entity = "Document", action = "SetRelationship", thread_safe = true)]
#[macros::uow_action(entity = "Frame", action = "Get", thread_safe = true)]
#[macros::uow_action(entity = "Frame", action = "CreateOrphan", thread_safe = true)]
#[macros::uow_action(entity = "Frame", action = "Update", thread_safe = true)]
#[macros::uow_action(
    entity = "Frame",
    action = "UpdateWithRelationships",
    thread_safe = true
)]
#[macros::uow_action(entity = "Frame", action = "RemoveMulti", thread_safe = true)]
#[macros::uow_action(entity = "Frame", action = "GetRelationship", thread_safe = true)]
#[macros::uow_action(entity = "Frame", action = "SetRelationship", thread_safe = true)]
#[macros::uow_action(entity = "Block", action = "Create", thread_safe = true)]
#[macros::uow_action(entity = "Block", action = "CreateOrphan", thread_safe = true)]
#[macros::uow_action(entity = "Block", action = "SetRelationship", thread_safe = true)]
#[macros::uow_action(entity = "List", action = "CreateOrphan", thread_safe = true)]
#[macros::uow_action(entity = "Table", action = "CreateOrphan", thread_safe = true)]
#[macros::uow_action(entity = "Table", action = "SetRelationship", thread_safe = true)]
#[macros::uow_action(entity = "TableCell", action = "CreateOrphan", thread_safe = true)]
pub trait ImportMarkdownUnitOfWorkTrait: CommandUnitOfWork + Send + Sync {}

pub struct ImportMarkdownUseCase {
    uow_factory: Box<dyn ImportMarkdownUnitOfWorkFactoryTrait>,
    dto: ImportMarkdownDto,
}

impl ImportMarkdownUseCase {
    pub fn new(
        uow_factory: Box<dyn ImportMarkdownUnitOfWorkFactoryTrait>,
        dto: &ImportMarkdownDto,
    ) -> Self {
        ImportMarkdownUseCase {
            uow_factory,
            dto: dto.clone(),
        }
    }
}

struct FrameState {
    frame_id: EntityId,
    child_order: Vec<i64>,
    /// The frame's `blocks`, in creation order, written to it once when it
    /// closes. See [`OrphanedChildren`].
    blocks: Vec<EntityId>,
}

/// What the walk creates without an owner, in creation order, until each owner
/// receives its whole list in one write.
///
/// Creating a child *with* its owner appends it to the owner's list, and that
/// append rewrites the entire list, fetches every entity it names to validate
/// it, and announces the entire list in an event. One append per paragraph made
/// loading N paragraphs cost N(N+1)/2 of those: a novel kept in one document
/// took seconds to open. Ids are handed out in the same order either way, so
/// the document stored at the end is the same.
#[derive(Default)]
struct OrphanedChildren {
    /// Every frame the import creates: the document's `frames`.
    frames: Vec<EntityId>,
    /// The document's new `lists`.
    lists: Vec<EntityId>,
    /// The document's new `tables`.
    tables: Vec<EntityId>,
}

impl OrphanedChildren {
    /// Give the document its new frames, lists and tables, one write each, after
    /// whatever it already holds: its lists and tables outlive a re-import, while
    /// its frames were all removed first.
    fn attach(
        self,
        uow: &mut Box<dyn ImportMarkdownUnitOfWorkTrait>,
        doc_id: EntityId,
    ) -> Result<()> {
        for (field, children) in [
            (DocumentRelationshipField::Frames, self.frames),
            (DocumentRelationshipField::Lists, self.lists),
            (DocumentRelationshipField::Tables, self.tables),
        ] {
            if children.is_empty() {
                continue;
            }
            let mut ids = uow.get_document_relationship(&doc_id, &field)?;
            ids.extend(children);
            uow.set_document_relationship(&doc_id, &field, &ids)?;
        }
        Ok(())
    }
}

/// Give a frame the blocks created for it, in one write.
fn attach_blocks(
    uow: &mut Box<dyn ImportMarkdownUnitOfWorkTrait>,
    frame_id: EntityId,
    blocks: &[EntityId],
) -> Result<()> {
    if blocks.is_empty() {
        return Ok(());
    }
    uow.set_frame_relationship(&frame_id, &FrameRelationshipField::Blocks, blocks)
}

/// Advance the blockquote frame stack to match `target_depth`, finalising
/// frames that close (writing back their `blocks` and `child_order`) and
/// creating new blockquote sub-frames as depth increases. Resets
/// `list_grouper` on every frame boundary so lists never group across
/// blockquote boundaries.
///
/// Touches only Frame entities — never the rope — so rope mirroring and
/// `document_position` bookkeeping in the caller are unaffected.
fn transition_bq_depth(
    uow: &mut Box<dyn ImportMarkdownUnitOfWorkTrait>,
    orphans: &mut OrphanedChildren,
    frame_stack: &mut Vec<FrameState>,
    current_bq_depth: &mut u32,
    target_depth: u32,
    list_grouper: &mut ListGrouper,
) -> Result<()> {
    // Close blockquote frames if depth decreased
    while *current_bq_depth > target_depth && frame_stack.len() > 1 {
        let finished = frame_stack.pop().unwrap();
        attach_blocks(uow, finished.frame_id, &finished.blocks)?;
        let mut frame_entity = uow
            .get_frame(&finished.frame_id)?
            .ok_or_else(|| anyhow!("Blockquote frame not found"))?;
        frame_entity.child_order = finished.child_order;
        uow.update_frame(&frame_entity)?;
        *current_bq_depth -= 1;
        list_grouper.reset();
    }

    // Open blockquote frames if depth increased
    while *current_bq_depth < target_depth {
        let parent_frame_id = frame_stack.last().unwrap().frame_id;
        let bq_frame = Frame {
            fmt_is_blockquote: Some(true),
            fmt_position: Some(FramePosition::InFlow),
            parent_frame: Some(parent_frame_id),
            ..Frame::default()
        };
        let created_bq = uow.create_orphan_frame(&bq_frame)?;
        orphans.frames.push(created_bq.id);
        frame_stack
            .last_mut()
            .unwrap()
            .child_order
            .push(-(created_bq.id as i64));
        frame_stack.push(FrameState {
            frame_id: created_bq.id,
            child_order: Vec::new(),
            blocks: Vec::new(),
        });
        *current_bq_depth += 1;
        list_grouper.reset();
    }

    Ok(())
}

/// Put `block_id` in the list `parsed` is an item of: the list `list_grouper`
/// holds open at its level when the item continues it, a new one otherwise. A
/// block that is no list item ends every open list.
fn assign_list(
    uow: &mut Box<dyn ImportMarkdownUnitOfWorkTrait>,
    orphans: &mut OrphanedChildren,
    list_grouper: &mut ListGrouper,
    parsed: &ParsedBlock,
    block_id: EntityId,
) -> Result<()> {
    let Some(list_style) = &parsed.list_style else {
        list_grouper.reset();
        return Ok(());
    };
    let list_id = match list_grouper.try_reuse(list_style, parsed.list_indent) {
        Some(existing_id) => existing_id,
        None => {
            let list = List {
                style: list_style.clone(),
                indent: parsed.list_indent as i64,
                ..List::default()
            };
            let created_list = uow.create_orphan_list(&list)?;
            orphans.lists.push(created_list.id);
            list_grouper.register(created_list.id, list_style.clone(), parsed.list_indent);
            created_list.id
        }
    };
    uow.set_block_relationship(
        &block_id,
        &common::direct_access::block::BlockRelationshipField::List,
        &[list_id],
    )
}

fn import_parsed_elements(
    uow: &mut Box<dyn ImportMarkdownUnitOfWorkTrait>,
    parsed_elements: &[ParsedElement],
    progress_callback: &dyn Fn(common::long_operation::OperationProgress),
    cancel_flag: &Arc<std::sync::atomic::AtomicBool>,
) -> Result<i64> {
    use std::sync::atomic::Ordering;

    progress_callback(common::long_operation::OperationProgress::new(
        10.0,
        Some("Parsed content, building document...".to_string()),
    ));

    // Step 1: Get Root and Document
    let root = uow
        .get_root(&ROOT_ENTITY_ID)?
        .ok_or_else(|| anyhow!("Root entity not found"))?;

    let doc_ids = uow.get_root_relationship(
        &root.id,
        &common::direct_access::root::RootRelationshipField::Document,
    )?;
    let doc_id = *doc_ids
        .first()
        .ok_or_else(|| anyhow!("Root has no associated Document"))?;

    // Step 2: Remove existing frames, in one call: each single removal rescans
    // every remaining frame, so one at a time is quadratic in the frames replaced.
    let frame_ids = uow.get_document_relationship(&doc_id, &DocumentRelationshipField::Frames)?;
    uow.remove_frame_multi(&frame_ids)?;

    if cancel_flag.load(Ordering::Relaxed) {
        return Err(anyhow!("Operation was cancelled"));
    }

    progress_callback(common::long_operation::OperationProgress::new(
        20.0,
        Some("Creating new document structure...".to_string()),
    ));

    // Step 3: Create root frame
    let mut orphans = OrphanedChildren::default();
    let new_frame = Frame::default();
    let created_frame = uow.create_orphan_frame(&new_frame)?;
    orphans.frames.push(created_frame.id);

    // Reset the rope+block_offsets before populating new content
    // (importers replace the entire document). No-op under default
    // backend.
    rope_reset(&uow.store());

    // Step 4: Create blocks with format runs and image anchors
    let total_elements = parsed_elements.len();
    let mut total_chars: i64 = 0;
    let mut total_block_count: i64 = 0;
    let mut document_position: i64 = 0;

    // Stack of frames: index 0 = root frame, deeper = nested blockquote frames
    let mut frame_stack: Vec<FrameState> = vec![FrameState {
        frame_id: created_frame.id,
        child_order: Vec::new(),
        blocks: Vec::new(),
    }];
    let mut current_bq_depth: u32 = 0;
    let mut list_grouper = ListGrouper::new();
    // Tracks whether at least one main-flow block has been appended
    // to the rope. Used to decide when to emit an inter-block `\n`
    // boundary (between blocks, not before the first). Table-cell
    // blocks are NOT counted — they live in separate rope ranges
    // per plan §1.6 and are deferred to step 5.5.
    let mut emitted_any_main_block = false;

    for (i, parsed_element) in parsed_elements.iter().enumerate() {
        if cancel_flag.load(Ordering::Relaxed) {
            return Err(anyhow!("Operation was cancelled"));
        }

        match parsed_element {
            // A footnote definition becomes a **detached** frame carrying the
            // label: owned by the document, in no frame's `child_order`, so it
            // never appears in the flow the editor lays out. Writers reach it by
            // label when they place the note. The frame is the same shape a
            // table cell gets — arbitrary block content needs a frame — but
            // deliberately not mirrored into the rope, because a note's body is
            // not part of the prose whose offsets the document addresses.
            // Mirrors `import_djot_uc`'s handling exactly, since `parse_markdown`
            // produces the same `ParsedElement::FootnoteDefinition` shape.
            ParsedElement::FootnoteDefinition { label, blocks } => {
                let note_frame = uow.create_orphan_frame(&Frame {
                    footnote_label: Some(label.clone()),
                    ..Frame::default()
                })?;
                orphans.frames.push(note_frame.id);

                let mut child_order: Vec<i64> = Vec::with_capacity(blocks.len());
                let mut note_blocks: Vec<EntityId> = Vec::with_capacity(blocks.len());
                // A note's lists are its own: they neither continue a list of the
                // prose nor go on in the prose after it.
                let mut note_lists = ListGrouper::new();
                for nb in blocks.iter() {
                    let ParsedInline {
                        plain_text,
                        runs: format_runs,
                        images: block_images,
                        footnote_refs: block_footnote_refs,
                    } = format_runs_from_spans(&nb.spans, nb.is_code_block);

                    // The document-wide running position, not an index within
                    // the note. `document_position` keys the block-offset index
                    // that `block_content_via_store` reads through, so a
                    // definition restarting at 0 collides with the prose and the
                    // index hands back byte ranges belonging to another block —
                    // which slices mid-`U+FFFC` and panics the rope.
                    let line_len = plain_text.chars().count() as i64;
                    let block = Block {
                        document_position,
                        fmt_heading_level: nb.heading_level,
                        fmt_marker: nb.marker.clone(),
                        fmt_is_code_block: Some(nb.is_code_block),
                        fmt_code_language: nb.code_language.clone(),
                        ..Block::default()
                    };
                    let created = uow.create_orphan_block(&block)?;
                    child_order.push(created.id as i64);
                    note_blocks.push(created.id);
                    // A list item of the note stays one: this used to drop the
                    // list, so a list written in a note came back from a save as
                    // plain paragraphs.
                    assign_list(uow, &mut orphans, &mut note_lists, nb, created.id)?;

                    // Mirrored into the rope like any other block: a definition
                    // is real document content, and `block_content_via_store` is
                    // the only way its text is ever read back.
                    //
                    // The boundary `\n` first, exactly as the main walk does.
                    // `rope_append_block` writes no separator of its own, so
                    // without this the preceding block's range runs straight
                    // into the note — and since a block's content is its range
                    // minus one trailing byte, the prose gets sliced one byte
                    // short, landing inside the three bytes of a `U+FFFC` and
                    // panicking the rope.
                    if emitted_any_main_block {
                        rope_insert_block_boundary(&uow.store());
                        document_position += 1;
                    }
                    rope_append_block(&uow.store(), created.id, &plain_text);
                    emitted_any_main_block = true;
                    document_position += line_len;

                    let store = uow.store();
                    if !format_runs.is_empty() {
                        store.format_runs.write().insert(created.id, format_runs);
                    }
                    if !block_images.is_empty() {
                        store.block_images.write().insert(created.id, block_images);
                    }
                    if !block_footnote_refs.is_empty() {
                        store
                            .block_footnote_refs
                            .write()
                            .insert(created.id, block_footnote_refs);
                    }
                }

                attach_blocks(uow, note_frame.id, &note_blocks)?;
                let mut updated = note_frame.clone();
                updated.child_order = child_order;
                uow.update_frame(&updated)?;
            }
            ParsedElement::Block(parsed_block) => {
                transition_bq_depth(
                    uow,
                    &mut orphans,
                    &mut frame_stack,
                    &mut current_bq_depth,
                    parsed_block.blockquote_depth,
                    &mut list_grouper,
                )?;

                let ParsedInline {
                    plain_text,
                    runs: format_runs,
                    images: block_images,
                    footnote_refs: block_footnote_refs,
                } = format_runs_from_spans(&parsed_block.spans, parsed_block.is_code_block);
                let line_len = plain_text.chars().count() as i64;

                // Create Block for the current (possibly blockquote) frame,
                // which receives it when it closes.
                let block = Block {
                    document_position,
                    fmt_heading_level: parsed_block.heading_level,
                    fmt_is_code_block: if parsed_block.is_code_block {
                        Some(true)
                    } else {
                        None
                    },
                    fmt_code_language: parsed_block.code_language.clone(),
                    ..Block::default()
                };

                let created_block = uow.create_orphan_block(&block)?;

                // Insert an inter-block `\n` into the global rope
                // before every block after the first.
                if emitted_any_main_block {
                    rope_insert_block_boundary(&uow.store());
                }
                rope_append_block(&uow.store(), created_block.id, &plain_text);
                emitted_any_main_block = true;

                {
                    let store = uow.store();
                    let mut runs_map = store.format_runs.write();
                    if !format_runs.is_empty() {
                        runs_map.insert(created_block.id, format_runs);
                    } else {
                        runs_map.remove(&created_block.id);
                    }
                    // Image anchors travel with the runs: both index into the same
                    // block text, which already carries each image's U+FFFC sentinel.
                    let mut images_map = store.block_images.write();
                    if !block_images.is_empty() {
                        images_map.insert(created_block.id, block_images);
                    } else {
                        images_map.remove(&created_block.id);
                    }
                    // Footnote references index into the same block text.
                    let mut notes_map = store.block_footnote_refs.write();
                    if !block_footnote_refs.is_empty() {
                        notes_map.insert(created_block.id, block_footnote_refs);
                    } else {
                        notes_map.remove(&created_block.id);
                    }
                    // Image anchors travel with the runs: both index into the
                    // same block text, which already carries each image's
                    // U+FFFC sentinel from `format_runs_from_spans`.
                }

                assign_list(
                    uow,
                    &mut orphans,
                    &mut list_grouper,
                    parsed_block,
                    created_block.id,
                )?;

                let current_frame = frame_stack.last_mut().unwrap();
                current_frame.child_order.push(created_block.id as i64);
                current_frame.blocks.push(created_block.id);
                total_chars += line_len;
                total_block_count += 1;

                document_position += line_len;
                if i < total_elements - 1 {
                    document_position += 1;
                }
            }

            ParsedElement::Table(parsed_table) => {
                // Synchronise the blockquote frame stack with the table's
                // depth so a table inside (or right after) a blockquote
                // lands in the correct frame.
                transition_bq_depth(
                    uow,
                    &mut orphans,
                    &mut frame_stack,
                    &mut current_bq_depth,
                    parsed_table.blockquote_depth,
                    &mut list_grouper,
                )?;

                // A table always interrupts a list, regardless of depth.
                list_grouper.reset();
                let num_rows = parsed_table.rows.len() as i64;
                let num_cols = parsed_table.rows.first().map_or(0, |r| r.len()) as i64;
                if num_rows == 0 || num_cols == 0 {
                    continue;
                }

                // 1. Create Table entity (owned by Document)
                let table = Table {
                    rows: num_rows,
                    columns: num_cols,
                    column_widths: vec![],
                    ..Table::default()
                };
                let created_table = uow.create_orphan_table(&table)?;
                orphans.tables.push(created_table.id);

                // 1b. Mirror the table-anchor sentinel into the global
                // rope. Appended at the end (the importer processes
                // elements linearly). The boundary comes from the same
                // positional flag every block uses — see the note on
                // `rope_append_table_anchor`.
                rope_append_table_anchor(&uow.store(), created_table.id, emitted_any_main_block);

                // 2. Create cell frames with content + TableCell entities
                let current_frame_id = frame_stack.last().unwrap().frame_id;
                let total_cells = num_rows * num_cols;
                let mut cell_count: i64 = 0;
                let mut created_cell_frame_ids: Vec<common::types::EntityId> = Vec::new();
                // The table's `cells`, written to it in one go below.
                let mut created_cell_ids: Vec<EntityId> = Vec::new();

                for (r, row) in parsed_table.rows.iter().enumerate() {
                    for (c, cell) in row.iter().enumerate() {
                        // Create cell frame
                        let cell_frame = Frame::default();
                        let created_cell_frame = uow.create_orphan_frame(&cell_frame)?;
                        orphans.frames.push(created_cell_frame.id);
                        created_cell_frame_ids.push(created_cell_frame.id);

                        let ParsedInline {
                            plain_text,
                            runs: format_runs,
                            images: block_images,
                            footnote_refs: block_footnote_refs,
                        } = format_runs_from_spans(&cell.spans, false);

                        // Create block in cell frame
                        let block = Block {
                            document_position,
                            ..Block::default()
                        };
                        let created_block = uow.create_block(&block, created_cell_frame.id, -1)?;

                        {
                            let store = uow.store();
                            let mut runs_map = store.format_runs.write();
                            if !format_runs.is_empty() {
                                runs_map.insert(created_block.id, format_runs);
                            } else {
                                runs_map.remove(&created_block.id);
                            }
                            // Image anchors travel with the runs: both index into the same
                            // block text, which already carries each image's U+FFFC sentinel.
                            let mut images_map = store.block_images.write();
                            if !block_images.is_empty() {
                                images_map.insert(created_block.id, block_images);
                            } else {
                                images_map.remove(&created_block.id);
                            }
                            // Footnote references index into the same block text.
                            let mut notes_map = store.block_footnote_refs.write();
                            if !block_footnote_refs.is_empty() {
                                notes_map.insert(created_block.id, block_footnote_refs);
                            } else {
                                notes_map.remove(&created_block.id);
                            }
                        }

                        // Mirror the cell block into the global rope:
                        // insert a `\n` boundary, then the cell's
                        // content.
                        rope_insert_block_boundary(&uow.store());
                        rope_append_block(&uow.store(), created_block.id, &plain_text);

                        // Update cell frame's child_order
                        let mut updated_cell_frame = created_cell_frame.clone();
                        updated_cell_frame.child_order = vec![created_block.id as i64];
                        uow.update_frame(&updated_cell_frame)?;

                        // Create TableCell entity
                        let table_cell = TableCell {
                            row: r as i64,
                            column: c as i64,
                            row_span: 1,
                            column_span: 1,
                            cell_frame: Some(created_cell_frame.id),
                            ..TableCell::default()
                        };
                        let created_cell = uow.create_orphan_table_cell(&table_cell)?;
                        created_cell_ids.push(created_cell.id);

                        let text_length = plain_text.chars().count() as i64;
                        total_chars += text_length;
                        total_block_count += 1;
                        cell_count += 1;
                        document_position += text_length;
                        if cell_count < total_cells {
                            document_position += 1;
                        }
                    }
                }

                uow.set_table_relationship(
                    &created_table.id,
                    &TableRelationshipField::Cells,
                    &created_cell_ids,
                )?;

                // 3. Create anchor frame (links table to the flow)
                let anchor_frame = Frame {
                    parent_frame: Some(current_frame_id),
                    table: Some(created_table.id),
                    ..Frame::default()
                };
                let created_anchor = uow.create_orphan_frame(&anchor_frame)?;
                orphans.frames.push(created_anchor.id);

                // Backfill each cell frame's `parent_frame` to point at
                // the anchor frame. Cell frames are created before the
                // anchor (we don't know the anchor id yet), so this
                // can't be set at creation time. Without this, walking
                // up from a cell to find its containing table fails —
                // breaking `insert_table_uc`'s "is the cursor inside an
                // existing table?" check.
                for cell_frame_id in &created_cell_frame_ids {
                    if let Some(cf) = uow.get_frame(cell_frame_id)? {
                        let mut updated = cf;
                        updated.parent_frame = Some(created_anchor.id);
                        // `update_frame` is scalar-only and preserves
                        // the existing parent_frame to guard against
                        // stale-entity writes; use the relationship-
                        // aware variant so this write actually lands.
                        uow.update_frame_with_relationships(&updated)?;
                    }
                }

                // Add anchor to parent's child_order (negative = frame reference)
                frame_stack
                    .last_mut()
                    .unwrap()
                    .child_order
                    .push(-(created_anchor.id as i64));

                // Tables put content in the rope (the anchor sentinel
                // + cell blocks) — any subsequent main-flow block must
                // be preceded by a `\n` boundary, same as after a
                // Block.
                emitted_any_main_block = true;

                // Separator after the table
                if i < total_elements - 1 {
                    document_position += 1;
                }
            }
        }

        // Report progress
        if i % 10 == 0 {
            let pct = 20.0 + (i as f32 / total_elements as f32) * 70.0;
            progress_callback(common::long_operation::OperationProgress::new(
                pct,
                Some(format!("Processing element {}/{}", i + 1, total_elements)),
            ));
        }
    }

    // Close any remaining open blockquote frames
    while frame_stack.len() > 1 {
        let finished = frame_stack.pop().unwrap();
        attach_blocks(uow, finished.frame_id, &finished.blocks)?;
        let mut frame_entity = uow
            .get_frame(&finished.frame_id)?
            .ok_or_else(|| anyhow!("Blockquote frame not found"))?;
        frame_entity.child_order = finished.child_order;
        uow.update_frame(&frame_entity)?;
    }

    // Step 5: Update root frame blocks and child_order
    let root_state = frame_stack.pop().unwrap();
    attach_blocks(uow, root_state.frame_id, &root_state.blocks)?;
    let mut updated_frame = uow
        .get_frame(&root_state.frame_id)?
        .ok_or_else(|| anyhow!("Created frame not found"))?;
    updated_frame.child_order = root_state.child_order;
    uow.update_frame(&updated_frame)?;

    // Every frame, list and table the walk created goes to the document.
    orphans.attach(uow, doc_id)?;

    // Step 6: Update document stats
    let mut updated_doc = uow
        .get_document(&doc_id)?
        .ok_or_else(|| anyhow!("Document not found after import"))?;
    updated_doc.character_count = total_chars;
    updated_doc.block_count = total_block_count;
    uow.update_document(&updated_doc)?;

    Ok(total_block_count)
}

impl LongOperation for ImportMarkdownUseCase {
    type Output = ImportMarkdownResultDto;

    fn execute(
        &self,
        progress_callback: Box<dyn Fn(common::long_operation::OperationProgress) + Send>,
        cancel_flag: Arc<std::sync::atomic::AtomicBool>,
    ) -> Result<Self::Output> {
        use std::sync::atomic::Ordering;

        progress_callback(common::long_operation::OperationProgress::new(
            0.0,
            Some("Starting markdown import...".to_string()),
        ));

        // Parse markdown
        let parsed_elements = parse_markdown(&self.dto.markdown_text);

        let mut uow = self.uow_factory.create();
        uow.begin_transaction()?;

        let result = import_parsed_elements(
            &mut uow,
            &parsed_elements,
            &*progress_callback,
            &cancel_flag,
        );

        match result {
            Ok(block_count) => {
                if cancel_flag.load(Ordering::Relaxed) {
                    uow.rollback()?;
                    return Err(anyhow!("Operation was cancelled"));
                }
                // Plan §1.6 Frame.byte_range maintenance happens in
                // Transaction::commit.
                uow.commit()?;

                progress_callback(common::long_operation::OperationProgress::new(
                    100.0,
                    Some("completed".to_string()),
                ));

                Ok(ImportMarkdownResultDto { block_count })
            }
            Err(e) => {
                uow.rollback()?;
                Err(e)
            }
        }
    }
}
